### ISSUE TITLE
Layout/chief test blazons

### ISSUE THREAD

**Issue by mbasaglia** [drawshield/Drawshield-Code#130]
A list of blazons to go through and make sure they are correct

* [x] per pall celestial azure or and sable 1 sun in his splendour of the second in middle chief 3 triskele of the first in 3rd quarter 3 lozenge of the 3rd in 4th quarter
* [x] gules on a bordure azure 10 bezants a raven migrant sable
* [x] sable seme de acorn sprigs tenne leaved vert on a pale argent 3 squirrel statant brunatre
* [x] chausse argent and sable
* [x] quarterly argent and sable a box gules in 1st quarter a box gules in 4th quarter
* [x] argent an orle azure 2 pole axes gules in saltire
* [x] argent a chief wavy azure a arm embowed gules an anchor azure in flank
* [x] tierced per chevron lead argent bronze 3 chevronel gules
* [x] per saltire carnation and purpure a rabbit forepaw raised argent
* [x] vert on a chevron or cotticed argent 5 butterflies gules
* [x] vert a chevron or double-cotticed arg
* [x] vert a chevron or triple-cotticed arg
* [x] per chevron inverted lead and barry argent and steel
* [x] gyronny fleury gules and or and vair-en-point
* [x] paly azure and argent on a chief azure a cinquefoil argent impaled with or a sun sable in abyss a serpent erect gules in fess point a moon crescent inverted sable in chief
* [x] fleury argent and gules 3 piles azure
* [x] brunatre potenty gules a chief barry pily vert and or
* [x] per chief azure and or a lion rampant tail nowed argent
* [x] fretty argent and azure a fess quadrate gules a hexagon or in fess point smaller slightly higher charged with a sea dragon sable larger
* [x] vert a plate charged with an octofoil gu
* [x] argent a fess azure fleury argent 2 fox heads gules respecting each other in chief smaller higher a book closed azure garnished argent in nombril lower
* [x] gules a bordure compony argent and sable 6 hearts or
* [x] azure a lozenge voided or fimbriated or charged with 4 bezants 1,2,1 a fillet saltire or
* [x] vert 5 annulets argent conjoined in fess throughout
* [x] argent a pile gules charged with a cross barby or very much larger slightly lower
* [x] quarterly, 1st, vert an acorn bendwise or; 2nd, vert an oak leaf bendwise sinister or; 3rd, vert an oak leaf bendwise or; 4th, vert an acorn bendwise sinister or;; over all an escutcheon tierced per bend orange or and gules a gauntlet clenched argent; lower
* [x] carnation 4 piles inverted lead on a chief lead a sun carnation between 2 clouds carnation
* [x] Per fess argent and vert, a bear passant gules
* [x] bendy sinister rose and argent a chief sable charged with 4 martlets argent larger an enty-en-point sable
* [x] argent on a chevron sable cotticed between 3 hinds trippant sable a rose argent between 4 annulets argent dimidiated with sable on a chevron argent cotticed between 3 hinds trippant argent a rose sable between 4 annulets sable
* [x] steel a bend sinister murrey between 3 lily-pads murrey
* [x] sable on a cross or 3 annulets interlaced sable between 4 trinity knots sable
* [x] quarterly sable and bendy or and gules a square argent
* [x] erminois on a chevron sable a crescent pendent or much larger between 6 crosses crosslet or palewise much larger
* [x] ermine a top-half lion rampant or above a bottom-half lion rampant azure a bordure azure charged with 12 bezants
* [x] per fess wavy or and azure a pale counter-charged 3 shrimp gules further apart larger 3 scallops 1,2 or further apart smaller
* [x] bendy of 10 or semy of lizards vert and vert semy of trefoils or

**Comment by karlwilcox** [comment]
The "throughout" examples are correct, "conjoined in fess" means arranged side by side but touching, "conjoined in fess throughout" means side-by-side, touching and extending to the edge of the field.
