### ISSUE TITLE
(Suggestion) Add an “outlined” keyword

### ISSUE THREAD

**Issue by Supelia** [drawshield/Drawshield-Code#145]
An “outline” keyword would allow people to outline their escutcheon or blazon with a thin border of black, like seen on the Ravensburg district flag in Germany:
[https://en.wikipedia.org/wiki/List_of_district_flags_of_Germany#/media/File:Flagge_Landkreis_Ravensburg.svg](url)

**Comment by karlwilcox** [comment]
We recently added a "fillet bordure" which should meet this need (sorry, it isn't in the visual catalog yet)
![ravensburg](https://user-images.githubusercontent.com/3171760/119042988-74ce6c80-b9b0-11eb-915e-1fb9dc1af699.png)

But thanks for the suggestion
