### ISSUE TITLE
!todo pall in lower qtr does not extend far enough
!draw quarterly
1st & 4th ...

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#151]
!todo pall in lower qtr does not extend far enough
!draw quarterly
1st & 4th argent, a pall sable
2nd & 3rd gules, a saltire argent charged with a rose proper

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/120301852-a29ca500-c310-11eb-9bb7-af887a2f2fef.png)
