### ISSUE TITLE
!todo `in saltire` ignored for implied quarters
!draw quarterly
i. gules, fiv...

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#153]
!todo `in saltire` ignored for implied quarters
!draw quarterly
i. gules, five towers argent in saltire // unexpected but understandable, no complaint
ii. and iii. vert, five towers argent in saltire palewise // both are good
(iv. implied by i.) // BUG: the `in saltire` is ignored for an implied quarter
drawn in a square shape

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/120301570-57829200-c310-11eb-95eb-5393b021a481.png)

**Comment by karlwilcox** [comment]
Good catch! The sub-shield is now cloned rather than referenced.
