### ISSUE TITLE
!todo `a pallium`  is not symetrical with the center line - is smidge to sinister

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#158]
!todo `a pallium`  is not symetrical with the center line - is smidge to sinister
!draw tierced in pale gu orange and or
impaled with 
tierced in pale vert az and purpure; 
over the parts 
  a pallium arg 
  a crosslet formy per pale or and vert in fess point 
  shown very much smaller much smaller lower

**Comment by ericscheid** [comment]
See how the crosslet has different space left and right, and also the centre line between _or_ and _vert_ is not at the angled intersection

![image](https://user-images.githubusercontent.com/2605467/120666692-20f37580-c4d0-11eb-9b15-6e2943b9ff11.png)

**Comment by karlwilcox** [comment]
Nudged over a bit. The tassels are NOT symmetrical, but I don't think they are intended to be.
