### ISSUE TITLE
!todo placement of baton reversed is too low

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#159]
!todo placement of baton reversed is too low
!draw cendree, a baton reversed sable

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/120913472-caa65280-c6da-11eb-8f8a-ba44cfc9a570.png)

**Comment by karlwilcox** [comment]
The baton is incorrectly being identified as one of the ordinaries for which reversed actually means inverted.
