### ISSUE TITLE
!todo recognise `baton marshall` as synonym for `marshall's baton`; fix catalog too

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#161]
!todo recognise `baton marshall` as synonym for `marshall's baton`; fix catalog too
Don't understand: ..., a baton marshall [sable]...

**Comment by ericscheid** [comment]
![baton marshall](https://user-images.githubusercontent.com/2605467/120884597-4fd02f80-c627-11eb-9b61-8dbb38617234.png)

![marhsalls baton](https://user-images.githubusercontent.com/2605467/120884606-58c10100-c627-11eb-8743-2002337a38ad.png)

**Comment by karlwilcox** [comment]
Done, note that a baton on its own is a synonym for a bendlet sinister couped.

**Comment by ericscheid** [comment]
except `bendlet couped` doesn't get couped. see #167
