### ISSUE TITLE
!todo nowy or rounded escartelly?

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#162]
!todo nowy or rounded escartelly?
!draw or, 
a pale gules nowy // expected
a palet argent nowy // BUG? a rounded version of escartelly
an endorse sable nowy // BUG? a rounded version of escartelly

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/120908881-5ce63080-c6b2-11eb-92c4-ae64a1c1e7b6.png)


Same thing with `fess`
![image](https://user-images.githubusercontent.com/2605467/120908910-aa629d80-c6b2-11eb-9b04-001680cbe5c6.png)

**Comment by karlwilcox** [comment]
This was fixed by #269
