### ISSUE TITLE
!todo chevron nowy is borked

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#163]
!todo chevron nowy is borked
!draw or, a chevron gules nowy

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/120912763-6339d400-c6d5-11eb-85a6-e85eb5e9efc6.png)

**Comment by karlwilcox** [comment]
Man that is ugly...

**Comment by karlwilcox** [comment]
Same as #103

**Comment by karlwilcox** [comment]
Now better, but not perfect. Possibly need to mark underside of chevron for special handling of "once" lines but probably a bit much work.
