### ISSUE TITLE
!todo endorses dancetty are offset

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#164]
!todo endorses dancetty are offset
https://drawshield.net/cache/336c80a69a3ef7641c307086e6edc31e.png

**Comment by ericscheid** [comment]
```
or,
  2 endorses sable // for reference
  2 Endorses gules Dancetty // bugs: a) is offset b) same size as indented
```

endorses dancetty:
![image](https://user-images.githubusercontent.com/2605467/120912888-5ff31800-c6d6-11eb-87fe-d08d2fc5ec55.png)


endorses indented:
![image](https://user-images.githubusercontent.com/2605467/120912895-700af780-c6d6-11eb-8209-4659ab4ec0ec.png)

For comparison, a `fess dancetty` and a `bar dancetty`
![image](https://user-images.githubusercontent.com/2605467/120913457-ae0a1a80-c6da-11eb-8a6d-a8baf8236b97.png)

**Comment by karlwilcox** [comment]
I think it is to do with the start point for dancetty. Can't really compare the fess examples as the fess dancetty is (I think) hand drawn, while the bar dancetty is generated...

**Comment by karlwilcox** [comment]
Now fixed
