### ISSUE TITLE
!todo fess indented has opposing angles instead of alternating angles

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#166]
!todo fess indented has opposing angles instead of alternating angles
!draw or,
a bar gules indented enhanced // OK: angles are alternating
a fess sable indented abased // BUG: angles are opposite

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/120913652-f1b15400-c6db-11eb-9fbe-81cc88414de0.png)

**Comment by ericscheid** [comment]
For comparison, the two sizes of `fess dancetty` and `bar dancetty` are well formed

![image](https://user-images.githubusercontent.com/2605467/120913699-65536100-c6dc-11eb-90d2-0fd09007cf68.png)

**Comment by ericscheid** [comment]
On the other hand, wikipedia says this:
> An ordinary **indented** is bounded by small zigzags like a triangle wave, with **peaks on one side matching peaks on the other**. An ordinary **dancetty is similar, but with peaks matching troughs**, so that the width is constant; it also typically has fewer points than indented.

Either way, there' an inconsistency somewhere.

**Comment by karlwilcox** [comment]
Fixed by an earlier change

**Comment by karlwilcox** [comment]
And tweaked so that the dancetty is a bit bigger
