### ISSUE TITLE
!todo named arrangements `on a quarter` don't work

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#168]
!todo named arrangements `on a quarter` don't work
!draw Argent on a quarter azure nine cross crosslets in saltire of the field, over all a fillet cross throughout gules

**Comment by ericscheid** [comment]
That gets this:

![Argent on a quarter azure nine cross crosslets in saltire of the field, over all a fillet cross throughout gules](https://user-images.githubusercontent.com/2605467/120916577-bd469380-c6ed-11eb-8029-07b85aa14c14.png)

It should get this (achieved via explicit quartering, not `on a quarter`):

![Quarterly 
  1st
    Azure 
      9 cross crosslets palewise in saltire argent
        smaller, closer together, higher and to dexter
  2nd, 3rd, 4th
    Argent;;
Over all 
  A fillet cross gules
Drawn on an SCA shape 
  with wikipedia tinctures
    in a flat style
-- Arms of the Episcopal Church](https://user-images.githubusercontent.com/2605467/120916597-d51e1780-c6ed-11eb-9e95-c39e3d241d12.png)

**Comment by ericscheid** [comment]
Note that the in saltire doesn't work on a canto, either.
!draw Argent on a canton azure nine cross crosslets in saltire of the field, over all a fillet cross throughout gules
![image](https://user-images.githubusercontent.com/2605467/120916848-47dbc280-c6ef-11eb-891a-876d49305bff.png)

**Comment by karlwilcox** [comment]
fixed for both
