### ISSUE TITLE
!todo add synonyms `pomeis` and `pomey` for `pomme`

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#169]
!todo add synonyms `pomeis` and `pomey` for `pomme`
Contact Form: Message: Don't understand: ...a [pomeis] in sinister [chief]... 
Blazon: gules a pomeis in sinister chief

Reference: Error Report

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/120916934-dea87f00-c6ef-11eb-9a7a-e9a67cbb4857.png)
