### ISSUE TITLE
!todo draw-bot disagrees with web-bot for tierced in pale

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#171]
!todo draw-bot disagrees with web-bot for tierced in pale
!draw gules
a chief tierced in pale or sable or

**Comment by ericscheid** [comment]
On the website, this renders correctly. The save-as-png code is flunking (even from website).

![image](https://user-images.githubusercontent.com/2605467/120984121-aec7ad00-c7bd-11eb-91b3-964d58fee323.png)

**Comment by karlwilcox** [comment]
This is a problem with imageMagick (which does the SVG to PNG conversion) not DrawShield directly (the generated SVG is correct). It works correctly on my development box so I probably need to get some updated libraries installed on the live system...

**Comment by karlwilcox** [comment]
Yes, this needed updated Inkscape libraries. This may also fix other, PNG related, rendering issues too.
