### ISSUE TITLE
!todo create new lion sejant guardant from parts

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#175]
!todo create new lion sejant guardant from parts
Haven't found a good image source yet I'm afraid, Heraldic Art (as usual) has the best selection but doesn't include it http://heraldicart.org/lion/ If we can find an affronty lion drawn with a similar style to a sejant one it might be possible to do a head transplant (under anaesthetic of course) - perhaps the head of "Lion Statant Guardant" might fit fairly well on the body of "Lion sejeant 1". What do folks think?

**Comment by Jackalgirl** [comment]
Would you like it in the Graham Johnston style?

**Comment by karlwilcox** [comment]
Yes, please - the other lions generally follow the pattern of the Lions shown in “a complete guide…” so they are a bit skinnier and more angular than the real thing!

**Comment by Jackalgirl** [comment]
Very good!  I can do this. : )

**Comment by Jackalgirl** [comment]
Gah!  I realized that I sent you that file I kit-bashed together and called it "regardant", when it's really just "guardant" (and it's labelled that way in DrawShield) -- IIRC, regardant would be looking in the sinister direction, over its shoulder.  I always get those two mixed up!  Do you need a sejant regardant lion?

**Comment by PaoloRuben** [comment]
![couchant-guardant](https://user-images.githubusercontent.com/57675116/183965309-38faaadd-93f8-4e08-91dd-ac11d0582b6d.svg)
Does this work?

**Comment by PaoloRuben** [comment]
created from parts already in drawshields no copyright issues

**Comment by PaoloRuben** [comment]
![lion-couchant-guardant](https://user-images.githubusercontent.com/57675116/186772715-aa214083-cc45-4719-b3e2-28aafbbbdd3e.svg)

**Comment by PaoloRuben** [comment]
I fixed it and should be almost ready for upload, just I don't know how to add ids
