### ISSUE TITLE
!todo spurious parsing fail of "and" in supporters

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#177]
!todo spurious parsing fail of "and" in supporters
!draw sable, a lion rampant or armed and langued gules
achievement a peers helmet cendree // just to force postioning
supporters a lion rampant or armed and langued gules // note the "and" throws an error here in supporters, but it didn't in the shield

**Comment by ericscheid** [comment]
The supporters were successfully armed and langued, but the "and" still irritated the parser.

![image](https://user-images.githubusercontent.com/2605467/121720477-8249c300-cb26-11eb-9d3c-d24eb7128d34.png)

The arming and langueing of the supporters wasn't implied by the prior charge.
```
sable, a lion rampant or armed and langued azure
achievement a peers helmet cendree
supporters a lion rampant or armed and langued gules
```
![image](https://user-images.githubusercontent.com/2605467/121720853-e9677780-cb26-11eb-8042-458adf1b10cc.png)

**Comment by karlwilcox** [comment]
Sorted. Hopefully will not have any side effects...
