### ISSUE TITLE
!todo parse supporters `in dexter` or `in sinister`

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#178]
!todo parse supporters `in dexter` or `in sinister`
Contact Form: Message: Do not understand position royal crown or supporter in dexter  near  near line 19 Do not understand position armed azure much wider in sinister  near  near line 20 Don't understand: ...dexter lion rampant argent langued [and] armed azure much wider... 
Blazon: quartered
 I per pale gules and azure
 a lion grady in annulo argent armed and langued azure
 II quartered
  i and iv or
  ii and iii argent a cross between 4 fleurs-de-lys sable
  over the quarters on a bend gules 3 hearts palewise argent
 III barry argent and azure
 a sword argent hilted or inverted shewn higher, slightly smaller
 an eastern crown argent shewn smaller, very much smaller, much wider, very much wider, slightly higher
 a bordure or
 IV per pale gules and azure
 a lion grady in annulo argent armed and langued azure shewn smaller, wider, higher
achievement
royal helmet
torse gules and argent
mantling gules and ermine
crest a royal crown or 
supporter in dexter lion rampant argent langued and armed azure much wider
in sinister gryphon rampant gules much wider
motto "Inkt Goedt Haade Vaej"
compartment a shelf bronze
Reference: Error Report

**Comment by ericscheid** [comment]
Ordinarily there is no need to specify supporter `in dexter` or `in sinister`.

Some users might however specify it.

If one supporter is specified it will be used on both sides, if two then parser assumes first is dexter and 2nd is sinister.
Parser should understand that though, not throw a spurious error (and maybe swap if writted in reverse order).

**Comment by ericscheid** [comment]
Ah, `to sinister` and `to dexter` both work. So more a case of synonyms.

**Comment by karlwilcox** [comment]
This now works as expected.
