### ISSUE TITLE
!todo book closed garnished too generous with the ink

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#182]
!todo book closed garnished too generous with the ink
!draw per pale
1st argent a closed book cendree
2nd argent 
  a closed book cendree 
    clasped gules 
    garnished azure  // cover should have only the flowers coloured
    leaved vert

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/121798948-aa433e80-cc6c-11eb-95e4-a5d49988b6e5.png)

![image](https://user-images.githubusercontent.com/2605467/121798943-9e577c80-cc6c-11eb-91b3-3195d8795443.png)
