### ISSUE TITLE
!todo add `chaplet` to catalog (plants, or emblems?)

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#183]
!todo add `chaplet` to catalog (plants, or emblems?)
Chaplets do not appear in the visual catalog, at least that I or search can find.

**Comment by ericscheid** [comment]
It exists, but is not in catalog.

![image](https://user-images.githubusercontent.com/2605467/121841210-3878fc80-cd21-11eb-9b2b-034724719c67.png)

**Comment by ericscheid** [comment]
Which category did you put it into? I don't see it in plants, flowers, or emblems; and it doesn't appear via the Item Finder widget.

https://drawshield.net/catalog/charges/plant/index.html
https://drawshield.net/catalog/charges/flower/index.html
https://drawshield.net/catalog/charges/emblem/index.html

(Or is it in the catalog, but the catalog just hasn't been refreshed yet? If so please excuse my rush.)

**Comment by karlwilcox** [comment]
Apologies, I think I must have clicked on “close” instead of “comment and close”. What I meant to say was that it is now called the “chaplet”, it is under the “emblem” category and it has 4 flowers. I haven’t updated the item finder - must automate that process
