### ISSUE TITLE
!todo new bot command `!find`

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#184]
!todo new bot command `!find`
A suggestion for the bot .. like the !define command, some !keyword that does what the Item Finder widget does on the website, including partial matches, synonym matches, and possibly responding with images from the catalog (including the various notations for armed, langued, garnished, etc).

Maybe two forms of response: found many, so just list the terms, and found one exact match so show the full details (image, category, type, colours) and related terms.

Thus `!item chap` will responde with `chaplain symbol, chape ploye, chape, chaplet`, while `!item chape` responds with details of the `chape` charge and a mention of `chape ploye` for completeness. 

With this limiting of big responses the search can be expanded to include more than just the item name .. one could conceiveably do `!item plant` to get a list of plant charges, or `!item langued` to get a list of charges that can be langued.

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/122178219-b8da6180-cec9-11eb-8bea-1302a8a5bc47.png)

**Comment by karlwilcox** [comment]
There is a bot command !catalog which does something like this (and runs off the same source data as the item finder). I will add !find as a synonym. It does accept “*” as a wildcard, so !catalog horse* finds all the horse variants, but !catalog horse just shows the default charge of that name. Might be useful to add something like !findall horse which automatically adds the wildcards before and after…?

**Comment by ericscheid** [comment]
Ah, completely didn't see `!catalog` listed as a command. Mea culpa.

Could it be updated to include the details of the item .. when seeing https://drawshield.net//catalog/charges/emblem/chaplet.png I would never have guessed that the second tincture option was `slipped`.

**Comment by karlwilcox** [comment]
I've added !find, which means the same as !catalog, and !findall which automatically adds a wildcard. If there is a single match the command displays a picture and lists the colour coded features. I'm not sure how useful a search for all things that can be "slipped" would be so I haven't done that for now.
