### ISSUE TITLE
!todo in blazon editor, style the quarter indentifiers with (e.g.) underlines...

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#186]
!todo in blazon editor, style the quarter indentifiers with (e.g.) underlines (1st, 2nd, first, second, i. ii., etc)

**Comment by ericscheid** [comment]
This way it's a hint that `forth` (for e.g.) is not a recognised keyword.
![image](https://user-images.githubusercontent.com/2605467/122532136-8bc1b680-d063-11eb-9f5e-1365d0724cb1.png)

(and shouldn't be)

**Comment by karlwilcox** [comment]
This is a good idea! Thanks, I'll get on to this soon.
