### ISSUE TITLE
!todo add occitan cross, also fix tolouse cross in catalog

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#195]
!todo add occitan cross, also fix tolouse cross in catalog
Maybe we could add an occitan cross? I've already found .svg files for them 🙂
Like this one: https://commons.wikimedia.org/wiki/Category:Occitan_cross#/media/File:Creu_occitana_black.svg
Filled in it would look like this: https://commons.wikimedia.org/wiki/Category:Occitan_cross#/media/File:Toulouse-Cross.svg (and apparently known as a Toulouse cross)

**Comment by karlwilcox** [comment]
I've added this better version of the Cross of Toulouse and added Occitan Cross and Cross of Languedoc as synonynms. You can also have the filled version as "Cross of Toulouse filled"

**Comment by ericscheid** [comment]
The filled version needs it's catalog entry updated

![image](https://user-images.githubusercontent.com/2605467/123586950-df34c100-d828-11eb-81a1-ca038a18dd5c.png)
