### ISSUE TITLE
!todo "Cross Pisa" in catalog should be "Cross of Pisa"

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#196]
!todo "Cross Pisa" in catalog should be "Cross of Pisa"

**Comment by karlwilcox** [comment]
Done

**Comment by ericscheid** [comment]
There is an additional entry on the [Symmetrical Crosses](https://drawshield.net/catalog/charges/quadrate/) page for `cross Pisa` which would appear to be wrong as `a cross Pisa grey` produces an error and the fallback cross. This additional `cross Pisa` should be removed from the catalogue.

<img width="677" alt="image" src="https://user-images.githubusercontent.com/2605467/174473314-42af5f0c-c2b1-4d6b-a2d7-a80fc9949288.png">

![image](https://user-images.githubusercontent.com/2605467/174473690-20c251ad-3520-463a-888a-4cd75bad1d3f.png)
