### ISSUE TITLE
!todo `ford` pushed off field by chief

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#200]
!todo `ford` pushed off field by chief
!draw arg a chief enhanced gu charged with three mullets or a Swan Nageant arg beaked orange a ford

**Comment by ericscheid** [comment]
Examining the svg xml shows there is an element with `<title>ford</title>`
![image](https://user-images.githubusercontent.com/2605467/124954023-02494700-e059-11eb-9b8a-73392082e558.png)

but given that the swan itself is also pushed downwards I suspect the ordinary has been also pushed downwards
![image](https://user-images.githubusercontent.com/2605467/124954349-4fc5b400-e059-11eb-9a36-34babfe8df65.png)

and on a partitioned field it gets worse:
![image](https://user-images.githubusercontent.com/2605467/124955093-1fcae080-e05a-11eb-870e-d50fae02a2bd.png)

**Comment by karlwilcox** [comment]
Fixed elsewhere
