### ISSUE TITLE
!todo ships wheel isn't exactly centred on the vertical

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#206]
!todo ships wheel isn't exactly centred on the vertical
!draw or,
a crosslet gules stroked or
a ships wheel tenne in fess point
a maltese cross sable stroked sa shown very much smaller

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/125894943-977aa45d-d451-469b-80d0-2e3156618685.png)

**Comment by karlwilcox** [comment]
This is what happens why you do things "by eye". Will fix...

**Comment by karlwilcox** [comment]
Done
