### ISSUE TITLE
!todo rat does not like being stroked

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#209]
!todo rat does not like being stroked
!draw or a rat tenne fimbriated gu stroked sable // neither imbriation or stroking effective

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/126055458-890b51d1-e852-4162-bb03-430ea884a450.png)

**Comment by karlwilcox** [comment]
The rat has been domesticated and you can also give him an itty-bitty little crown too, if you want to.

**Comment by ericscheid** [comment]
Something still not right .. `fimbriation` is colliding with `stroke`

Compare
![image](https://user-images.githubusercontent.com/2605467/126366213-ac224f1c-1ac2-4a97-84eb-1c76d78363f2.png)![image](https://user-images.githubusercontent.com/2605467/126366195-e9d03a08-e010-4582-baf5-99d4ca09f81b.png)
