### ISSUE TITLE
Add cat shown fancy

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#220]
To look something like the Koshkin cat:

![image](https://user-images.githubusercontent.com/3171760/128011235-b20f7892-7d31-48d6-984b-fb7e426baba5.png)

Might be able to modify one of the lions from here https://commons.wikimedia.org/wiki/Category:SVG_coat_of_arms_elements_-_lions_rampant by re-drawing the head and providing a new tail

**Comment by Jackalgirl** [comment]
Mmm, I like this cat a lot.  What is the source (which armorial)?

**Comment by karlwilcox** [comment]
I like it too, but that is the only image we can find - it is from here https://commons.wikimedia.org/wiki/File:RU_COA_Koshkin_XVIII,_104.jpg, which gives the original source as https://gerbovnik.ru/arms/2995 but I don't know any Russian so I can't tell you any more, sorry.

**Comment by Jackalgirl** [comment]
I did some digging - it's by I.V. Borisov (the author), and the original book is "General coat of arms of noble families of the All-Russian Empire", dates from 1904, and it's in the public domain.  Yippee!

<img width="414" alt="Koshkin family coat of arms, from the Russian armorial 'General coat of arms of noble families of the All-Russian Empire', traced and painted by Jackalgirl" src="https://user-images.githubusercontent.com/88459050/128257534-b272c6d8-072d-4122-835e-503ca239b117.png">

It should be fairly easy to convert this SVG.  I just need to import these into AI and trace them.  Should be done soon.

**Comment by karlwilcox** [comment]
Fixed, will close once catalog has been updated
