### ISSUE TITLE
!todo add more fox postures

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#229]
!todo add more fox postures

**Comment by karlwilcox** [comment]
I've added rampant and passant, I look if there are any other good ones.

**Comment by Jackalgirl** [comment]
Looks like you're leaning towards the Graham Johnson ("A Complete Guide to Heraldry") look for foxes at least; I think I can probably pull off a Fox Statant in that style if you think it'd be helpful.
