### ISSUE TITLE
!todo make dovetailed and nebuly less zealous

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#230]
!todo make dovetailed and nebuly less zealous

**Comment by ericscheid** [comment]
Both `dovetailed` and `nebuly` are over-zealous, it looks less like an edge treatment and more like bits barely attached.

![image](https://user-images.githubusercontent.com/2605467/130180977-b2afe564-1f8b-4490-9f65-df10855ba968.png)
![image](https://user-images.githubusercontent.com/2605467/130181213-cdb93c5a-92b2-4616-ba29-10bd79f3373c.png)

vs this from wikipedia:

![image](https://user-images.githubusercontent.com/2605467/130181016-dbf54b7d-c907-4fa2-8bba-82930adbfdda.png)
![image](https://user-images.githubusercontent.com/2605467/130181243-89317619-bc5c-47b0-911f-fbb03a927496.png)

**Comment by karlwilcox** [comment]
Agreed! This is in progress...
