### ISSUE TITLE
!todo `counter embattled` cuts into ordinary instead of attaching battlements

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#238]
!todo `counter embattled` cuts into ordinary instead of attaching battlements
!draw Vert,
  a fess Or debased 
  embattled counter embattled
  cotticed argent

**Comment by ericscheid** [comment]
```
per pale
I Argent, a fess Vert embattled cotticed Azure
II Argent, a fess Gules embattled counter embattled cotticed Azure
```
![image](https://user-images.githubusercontent.com/2605467/131297557-5f595f1a-8dbe-485a-8a04-01a523a01cb6.png)

**Comment by ericscheid** [comment]
Also occurs when `counter embattled` is applied to a `cottice`

![image](https://user-images.githubusercontent.com/2605467/131298018-57e5fa0b-6709-4809-8548-cda5524f3909.png)

**Comment by karlwilcox** [comment]
The recent mods to the fess edges has resolved this issue
