### ISSUE TITLE
!todo `bar counterchanged enhanced` does not show

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#244]
!todo `bar counterchanged enhanced` does not show
!draw chevronny brunatre and orange, a bar counterchanged enhanced

**Comment by ericscheid** [comment]
`bar counterchanged` works..
![bar counterchanged](https://user-images.githubusercontent.com/2605467/132011742-69cf18a7-db14-4e27-86e9-cae1911dab2f.png)

`bar sable enhanced` works..
![bar sable enhanced](https://user-images.githubusercontent.com/2605467/132011673-02ec2730-671e-4026-bc58-3f3bf6fbfef7.png)

`bar counterchanged enhanced` .. does not
![bar counterchanged enhanced](https://user-images.githubusercontent.com/2605467/132011643-27dc4656-38b0-4198-bddc-9ca7a08d8ddf.png)

The `bar counterchanged enhanced` is in the SVG..
![svg](https://user-images.githubusercontent.com/2605467/132014173-ea3964f8-3ff1-486d-864b-81a54dde2dc8.png)

It is shifted upwards the same as the `bar sable enhanced` .. fiddling with that -199 figure reveals the bar .. and oh! 

OK, I see what's happened ..
`chevronny brunatre and orange, a bar counterchanged enhanced fimbriated sable`
![bar counterchanged enhanced fimbriated sable](https://user-images.githubusercontent.com/2605467/132016079-69811f3b-332e-4a07-ba40-73f38a228242.png)

The `counterchanged` operation is performed first, where the bar is in normal fess position, and is then shifted upwards just precisely so such that the chevrons overlap once again. 

**The bar should be `enhanced` first, before it is then `counterchanged` against the underlying two tinctures in the enhanced location.**

**Comment by ericscheid** [comment]
Perfection =)

![image](https://user-images.githubusercontent.com/2605467/213906330-8dfb68a4-f626-4b6d-b7bb-431abccb3923.png)
