### ISSUE TITLE
!todo [tweak] adjust widths of `chevron voided cotticed`

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#251]
!todo [tweak] adjust widths of `chevron voided cotticed`
!draw gules, a chevron argent double cotticed voided 
// would be nice if the width of the remainders of `chevron voided` was the same width as the `cottices`

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/132315107-e4a41402-1a7a-43b9-bd6a-72f3fe58cf99.png)
