### ISSUE TITLE
!todo `a demi penguin`  is not top-half, unlike all other animals

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#255]
!todo `a demi penguin`  is not top-half, unlike all other animals
!draw quarterly, 
I vert, a demi lion or
II vert, a demi antelope or
III vert, a demi anteater or
IV gules, a demi penguin or // penguins are such rebellious rascals

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/133251658-f20c26cd-66ec-4bef-aaf7-850789f12b34.png)
