### ISSUE TITLE
!todo reindeer, you can have them in any colour so long as it is argent

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#256]
!todo reindeer, you can have them in any colour so long as it is argent
!draw gules, a reindeer or // sneaky bugger, hiding in the snow

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/133251599-2613991b-609c-4ca4-a185-89b10d80ebd9.png)
