### ISSUE TITLE
!todo shape and position of `fusil` needs work

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#257]
!todo shape and position of `fusil` needs work
!draw quarterly
I. gules 1 fusil or // not really "an elongated lozenge" here
II. vert 2 fusil or // this is more expected
III. gules 1 fusil or // uh .. shape is expected, but positioning is bad, tres bad
IV. gules 2 fusil in pale or // positioning ok, but shape is not-elongated

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/133253880-ec307936-0607-44d4-bd6c-ececec375e5d.png)

**Comment by karlwilcox** [comment]
Part fixed - I've stopped them getting too fat anyway!

**Comment by karlwilcox** [comment]
This actually applied to a group of single charges that appeared in the lower 2 of 4 quarters and has now been fixed
