### ISSUE TITLE
!todo fix per pall reversed bottom edge

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#258]
!todo fix per pall reversed bottom edge
!draw per pall reversed gules argent or // 3rd partition does not extend low enough

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/133341451-ca25d226-66c7-49c4-8fa2-d0fe81fbc08f.png)

**Comment by ericscheid** [comment]
Also, `per pall reversed` is not mentioned on https://drawshield.net/catalog/divisions/multi/

(found `per pall reversed` via https://fr.wikipedia.org/wiki/Saint-Barth%C3%A9lemy-Grozon#H%C3%A9raldique [after some translations])
