### ISSUE TITLE
!todo fix centering of `pall`

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#259]
!todo fix centering of `pall`
!draw per pall inverted argent gules argent, a pall inverted or
// the `pall inverted` is not centre aligned

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/133371603-74ccd247-900b-48fe-8a9b-8fc7e58a91b3.png)

**Comment by ericscheid** [comment]
Sorry, specifically the `pall inverted`.

Looks like the dimensions are slightly off as the end-point doesn't lead to the start-point
![image](https://user-images.githubusercontent.com/2605467/133373349-548b5bf4-f187-464d-ae30-774bcdbbbb33.png)

and also appears to slightly sinister:
![image](https://user-images.githubusercontent.com/2605467/133373686-dd1f4d59-9567-4b0d-a908-b6ad5c94270c.png)

**Comment by karlwilcox** [comment]
Interesting - somewhere the SVG <path> instructions are being truncated to 1 decimal place and the accumulated errors mean it is off center by the time it completes drawing the pall. Investigating further...
