### ISSUE TITLE
!todo fess angled doesn't flip the turtle on the way back

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#267]
!todo fess angled doesn't flip the turtle on the way back
!draw argent, a fess angled gules

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/135217540-d9834ea9-cfe1-4ef6-b994-57d39983be9a.png)

**Comment by karlwilcox** [comment]
Fixed by an previous change
