### ISSUE TITLE
!todo fess bevilled did not understand the assignment

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#268]
!todo fess bevilled did not understand the assignment
!draw argent, a fess bevilled gules

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/135217867-1d625619-8b97-49a5-a7ff-55270328e494.png)

**Comment by karlwilcox** [comment]
This particular one has been fixed but reveals an underlying issue with other edges, this needs a bit of an update to all edges to indicate where they should start and end so is taking a bit more time.

**Comment by karlwilcox** [comment]
Everything in svg/edges needs to marked up with data-drawshield-(start|end)="(inner|outer)" and the offsetting code needs to be copied from EdgeTypeRepeating to EdgeTypeFull

**Comment by karlwilcox** [comment]
For now I've reverted the fess to the old way of doing things, which isn't quite as flexible but doesn't have the issues above. Need to put some thought into how to fix the issues with Mutable_shape...
