### ISSUE TITLE
!todo fess escartelly doing something not right

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#269]
!todo fess escartelly doing something not right
!draw argent, a fess escartelly gules

**Comment by ericscheid** [comment]
Obviously, not applying the escartelly edge treatment, but also note how the fess is raised .. it is doing *something*, just not the *right* thing

![image](https://user-images.githubusercontent.com/2605467/135218520-a1221921-bef4-435f-ab0a-1cf18939f3b9.png)

**Comment by karlwilcox** [comment]
I'm going to fix this by adding a specific fess escartelly but the proper fix lies in some code in edge_types.inc in its handling of the "full" data type (only needed for escartelly and nowy)

**Comment by ericscheid** [comment]
Some similar shifty shenanigans happening with `base` and `chief`, and also `bend`

I would have expected the edge of the ordinaries to remain stable, with edge treatmens intruding and extruding. With the `bend` particularly it looks like the final dimensions are being aligned along the centre-line of the bend, and thus it shifts downwards by half the notch. This would also explain the shifting with `base` and `chief`.

<img width="542" alt="image" src="https://user-images.githubusercontent.com/2605467/209503134-15e5d429-eac6-4f69-b96e-96ddba920b41.png">

<img width="451" alt="image" src="https://user-images.githubusercontent.com/2605467/209503219-234dff65-5a45-4638-bba4-5cbe2425cc09.png">

**Comment by karlwilcox** [comment]
Actually, I'm smarter than I thought I was and I have fixed the problem in edge_types.inc. The second issue still remains however. I need to think about that one a bit.

**Comment by karlwilcox** [comment]
And now I think that one is fixed too.
