### ISSUE TITLE
!todo placeholder box for alphyn crowned is filled

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#271]
!todo placeholder box for alphyn crowned is filled
!draw Barry or and azure an alphyn sable

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/135544457-c4261c08-fe9a-4b14-b89d-5a96ccc8d884.png)

**Comment by karlwilcox** [comment]
Done
