### ISSUE TITLE
!todo `/random` unknown keys of [axes], [swords] (maybe more)

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#283]
!todo `/random` unknown keys of [axes], [swords] (maybe more)
Another `/random` fail — looks like it wanted to pick a random axe

**Comment by ericscheid** [comment]
Ah .. line 335 references `{swords}` and `{axes}` .. but lines 337 and 339 only define the singular terms.

https://github.com/drawshield/Drawshield-Code/blob/ed16c26e391a6afe82ba7e641067a590e3faffca/randomblazon.php#L331-L343

**Comment by karlwilcox** [comment]
Good spot Eric!

**Comment by karlwilcox** [comment]
fixed some time ago, sorry, forgot to update
