### ISSUE TITLE
!todo `per fess embattled in the form of mine dumps` broken

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#284]
!todo `per fess embattled in the form of mine dumps` broken
!draw per fess vert and gules embattled in the form of mine dumps

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/138903482-acb64814-57e4-4c75-b57e-a91f64bbf9fd.png)

Mostly works right if `per pale` .. although it is noticeably off-centre (look to the base point)
![image](https://user-images.githubusercontent.com/2605467/138903572-70e80e7c-acad-4a86-b3a3-4dc643dacff6.png)
