### ISSUE TITLE
!todo positioning of `two swords fesswise` is off

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#285]
!todo positioning of `two swords fesswise` is off
https://drawshield.net/cache/62c285e5ea3c40f23e69423fdc079145.png

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/139226144-11fdfcf3-01d7-442f-860f-66e45d29fa72.png)

**Comment by karlwilcox** [comment]
This now works correctly but the sword needs a colouring fix!
