### ISSUE TITLE
!todo add one supporter behind the shield

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#287]
!todo add one supporter behind the shield
hi @​Artifex Scutum  as part also of the Achievment Improvment Update, can we add a way to have 1 supporter behind the shield? Ive seen it in old manuscripts. Ive lost the orignal image, but ive tried my best to recreate. I was hoping it could blazon as *"az supporter an angel proper shewn behind the shield"* like these examples,

**Comment by ericscheid** [comment]
https://discord.com/channels/775325424854630440/775486526439817227/898205231706427392

Discussion arrived at the achievement of one supporter (only) being the exception with special syntax, likely by use of `a/an/one/`. That is, leave the default when count unstated to imply `two` supporters.

![image](https://user-images.githubusercontent.com/2605467/139377348-19d67a18-0cde-4cba-a955-a0f8c4547f16.png)

**Comment by karlwilcox** [comment]
This is done, although you will probably have to do your own sizing and positioning of the shield
