### ISSUE TITLE
!todo all mottos are silent

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#292]
!todo all mottos are silent
!test Or, on a cross gules, five mullets argent ; on a canton of the second a lion passant of the first.
Crest A lion sejant argent, ducally crowned or.
Motto "Deus nobis hæc otia fecit".

**Comment by ericscheid** [comment]
ooh .. correction .. the motto is misplaced (not missing), it is located in the far top-left.

![image](https://user-images.githubusercontent.com/2605467/140704858-ebd3e11c-6490-4669-afcc-87721b31673e.png)

**Comment by ericscheid** [comment]
Anyway, here's another 20 gallery links showing mottos that no longer work.

https://drawshield.net/gallery/66/gallery-6613.html
https://drawshield.net/gallery/49/gallery-4951.html
https://drawshield.net/gallery/84/gallery-8428.html
https://drawshield.net/gallery/51/gallery-5118.html
https://drawshield.net/gallery/90/gallery-9078.html
https://drawshield.net/gallery/62/gallery-6203.html
https://drawshield.net/gallery/91/gallery-9118.html
https://drawshield.net/gallery/59/gallery-5939.html
https://drawshield.net/gallery/87/gallery-8789.html
https://drawshield.net/gallery/55/gallery-5521.html
https://drawshield.net/gallery/59/gallery-5904.html
https://drawshield.net/gallery/49/gallery-4950.html
https://drawshield.net/gallery/88/gallery-8824.html
https://drawshield.net/gallery/49/gallery-4987.html
https://drawshield.net/gallery/86/gallery-8617.html
https://drawshield.net/gallery/49/gallery-4993.html
https://drawshield.net/gallery/49/gallery-4985.html
https://drawshield.net/gallery/90/gallery-9084.html
https://drawshield.net/gallery/50/gallery-5047.html
https://drawshield.net/gallery/69/gallery-6943.html

**Comment by karlwilcox** [comment]
Fixed this, apologies. Now on live system
