### ISSUE TITLE
!todo `an ostrich feather` is always shown as Or

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#294]
!todo `an ostrich feather` is always shown as Or
!draw 
quartered
  1) sa an ostrich feather gules
  2) sa an ostrich feather azure
  3) sa an ostrich feather vert
  4) sa an ostrich feather murrey

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/141455956-b4e91f6a-c026-4d36-8544-a16061862161.png)
