### ISSUE TITLE
!todo crests without helm now missing

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#296]
!todo crests without helm now missing

**Comment by ericscheid** [comment]
Examples from gallery

https://drawshield.net/gallery/59/gallery-5904.html

Old cached render, vs current render:


![old render](https://user-images.githubusercontent.com/2605467/142875732-a1d04d29-cbdd-4ec6-8db2-924e926aa039.png)
![new render](https://user-images.githubusercontent.com/2605467/142875029-715962f3-50f0-4e16-8abe-7da76e5002ca.png)

-----

more examples: 

https://drawshield.net/gallery/65/gallery-6598.html
https://drawshield.net/gallery/49/gallery-4990.html
https://drawshield.net/gallery/53/gallery-5318.html
https://drawshield.net/gallery/53/gallery-5334.html

**Comment by karlwilcox** [comment]
fixed, and what's more, you can have up to three of them!
