### ISSUE TITLE
!todo crosses palewise in saltire not working

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#298]
!todo crosses palewise in saltire not working
!draw Quarterly 
  1st
    Azure 
      9 cross crosslets palewise in saltire argent
        much closer together, higher and to dexter
  2nd, 3rd, 4th
    Argent;;
Over all 
  A fillet cross gules

**Comment by ericscheid** [comment]
Crosses not aligned despite `9 cross crosslets palewise in saltire argent`
![crosses not aligned](https://user-images.githubusercontent.com/2605467/142967458-5c90194d-fd86-4597-ac55-d39926077d25.png)

Should look like this, via `9 cross crosslets fesswise in saltire argent`
![crosses all aligned the same way](https://user-images.githubusercontent.com/2605467/142967613-93909d0d-ff82-426e-a834-634b13bbecf9.png)

Note: `9 cross crosslets bendwisewise in saltire argent` also behaves correctly.
![crosses all aligned the same way](https://user-images.githubusercontent.com/2605467/142967785-ab446c1a-dea1-4f2b-9a40-358315fd72e7.png)
