### ISSUE TITLE
!todo per chevron dancetty not centre aligned

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#307]
!todo per chevron dancetty not centre aligned
!draw per chevron dancetty or and gules

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/144744770-d6ef60b7-d899-4a66-9ccb-9259a998b8eb.png)

**Comment by karlwilcox** [comment]
fixed by some previous change
