### ISSUE TITLE
!todo saltire embattled mine dumps gone wrong

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#309]
!todo saltire embattled mine dumps gone wrong
!draw argent  a saltire embattled in the form of mine dumps gules

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/145498817-4453615f-6a02-4687-bb2f-12fff9d097e5.png)

**Comment by karlwilcox** [comment]
Fixed but ugly
