### ISSUE TITLE
!todo `fess embattled mine dumps` has mirror symmetry

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#310]
!todo `fess embattled mine dumps` has mirror symmetry
!draw quartered
i. argent, a fess embattled in the form of mine dumps gules // this looks wrong
ii. argent, a bar embattled in the form of mine dumps vert
iii. argent, a barrulet embattled in the form of mine dumps vert

iv. argent, a pale embattled in the form of mine dumps vert
v.  argent, a palet embattled in the form of mine dumps vert
vi. argent, an endorse embattled in the form of mine dumps vert

vii. argent, a bend embattled in the form of mine dumps vert
viii.  argent, a bendlet embattled in the form of mine dumps vert
ix. argent, a riband embattled in the form of mine dumps vert

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/145499909-84be73c6-12d8-45bc-8736-7876609ae8a2.png)
