### ISSUE TITLE
!todo `canadian pale` in catalog has wrong example image

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#311]
!todo `canadian pale` in catalog has wrong example image

**Comment by ericscheid** [comment]
The example image for `Canadian pale` looks like `pale voided` (which itself is the old wrong render, fixed in #281)

https://drawshield.net/catalog/ordinaries/pale/index.html

![image](https://user-images.githubusercontent.com/2605467/145500058-48121497-0392-49e3-b600-b82ad119ff9f.png)

**Comment by karlwilcox** [comment]
Correct version uploaded
