### ISSUE TITLE
!todo hatching fail with impaled

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#313]
!todo hatching fail with impaled
!draw barry azure argent impaled with or // a fess gules
drawn with a hatching palette

**Comment by ericscheid** [comment]
both bot and website do this

![image](https://user-images.githubusercontent.com/2605467/146357759-ae4e6e68-daa9-48d1-94e8-37cebbdc94ba.png)

![image](https://user-images.githubusercontent.com/2605467/146357965-06e2d0be-9152-4060-864d-234a87d1bb36.png)

![image](https://user-images.githubusercontent.com/2605467/146358026-af985d98-7e0c-4e52-96f8-bb54ba1d04fb.png)

**Comment by karlwilcox** [comment]
Not as easy as it looked, but done
