### ISSUE TITLE
!todo bot is glitching chief per pale

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#314]
!todo bot is glitching chief per pale
!draw sable, a chief per pale or and gules

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/146634574-90846be6-798d-4f93-a8b3-d3b479d0f2ce.png)

**Comment by karlwilcox** [comment]
Was fixed in the latest Inkscape libraries
