### ISSUE TITLE
!todo pall not extending to edge when impaled

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#315]
!todo pall not extending to edge when impaled
!draw argent, a pall gules, impaled with cendree

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/146634555-4c4d67f4-de50-4870-8dab-4d3a93378bef.png)

**Comment by karlwilcox** [comment]
Almost certainly the same problem as #321
