### ISSUE TITLE
!todo bot geometry fail with orle

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#316]
!todo bot geometry fail with orle
!draw per bend sable per bend sinister gules azure, an orle per bend sable argent

**Comment by ericscheid** [comment]
Note the bottom and right edges of the orle.

This does not happen on the web, this is a bot-only börkness.

![image](https://user-images.githubusercontent.com/2605467/146637872-bf5cee59-b8b3-4d56-a722-eb76e6f01d2e.png)

**Comment by karlwilcox** [comment]
Fixed by batik SVG renderer
