### ISSUE TITLE
!todo impaled patterns broken

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#321]
!todo impaled patterns broken
!draw arg impaled with fusily bendy gules or

**Comment by ericscheid** [comment]
## !draw arg impaled with fusily bendy gules or
![image](https://user-images.githubusercontent.com/2605467/147386377-8bdd0b41-5c78-452b-8914-e7d0d1b62fd2.png)

## !draw arg impaled with fusily
![image](https://user-images.githubusercontent.com/2605467/147386380-58803681-3e83-4526-954d-7e2b6913c723.png)

**Comment by karlwilcox** [comment]
Impaling isn’t implemented very well in general so this is probably part of a broader issue
