### ISSUE TITLE
!todo charge on a canadian pale mis-positioned

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#328]
!todo charge on a canadian pale mis-positioned
!draw gules, on a canadian pale argent, a maple leaf gules // bugged!

**Comment by ericscheid** [comment]
### gules, on a canadian pale argent, a maple leaf gules
![image](https://user-images.githubusercontent.com/2605467/148051566-ee12229d-b3c3-44fa-969a-bf113c225c94.png)

### gules, on a (canadian) pale argent, a maple leaf gules
![image](https://user-images.githubusercontent.com/2605467/148051648-08185ab9-9e72-44c9-8ac4-02d75c0ef466.png)

**Comment by karlwilcox** [comment]
duplicate #303
