### ISSUE TITLE
!todo dragon wings not stroked

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#329]
!todo dragon wings not stroked
!draw 
Per fess Argent and Vert, 
a dragon passant reversed Gules stroked Sable // bug: wings are not stroked
drawn in a flag shape

**Comment by ericscheid** [comment]
![This dragon tastes of sadness and shame](https://user-images.githubusercontent.com/2605467/148054849-d66f985f-04c1-4d53-9a4a-979716979678.png)

Can fake/force it though by inserting _winged Gules_..
`Per fess Argent and Vert, a dragon passant reversed Gules stroked Sable`
![Hwrê! Hir oes i Gymru ffynnu!](https://user-images.githubusercontent.com/2605467/148054908-e4e80db8-4fd6-4dd8-aa6e-8abe528a19fe.png)

The bot reports an parsing/rendering error though, which might be itself be an error:
> dragon-winged-passant-reversed may not be drawn with winged  undefined

![here we see the elusive blue winged welsh dragon...](https://user-images.githubusercontent.com/2605467/148055093-97d981d2-ef4a-46dc-a5cf-904c43dfd84b.png)

**Comment by karlwilcox** [comment]
Both problems fixed, ready for upload
