### ISSUE TITLE
!todo bot fails fess paly (3+ tinctures)

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#333]
!todo bot fails fess paly (3+ tinctures)
!draw sable, a fess couped enhanced paly or sable and argent
// bot produces a borked emblazon, as compared to drawshield.net/create

**Comment by ericscheid** [comment]
### should be this ...

![image](https://user-images.githubusercontent.com/2605467/148743514-92f700c3-f40d-4054-9908-f0f66ffd2d1f.png)

### !draw sable, a fess couped enhanced paly or sable and argent
![image](https://user-images.githubusercontent.com/2605467/148743383-70df5bc4-4cdc-46d1-9425-c8031ccb0896.png)

### !draw sable, a fess (couped) enhanced paly or sable and argent // hmm
![image](https://user-images.githubusercontent.com/2605467/148743564-5f193e9e-e598-4c72-9dea-deb69e242678.png)

### !draw sable, a fess (couped enhanced) paly or sable and argent // really simplified
![image](https://user-images.githubusercontent.com/2605467/148743597-c701db0d-65a4-47b1-aca9-e4265065c685.png)


### !draw sable, a fess paly or sable argent gules
![image](https://user-images.githubusercontent.com/2605467/148743637-c34b4af3-f5eb-4ff9-a481-bb4fa0ddcde1.png)


### !draw sable, a fess paly argent gules
**finally, something that works:**
![image](https://user-images.githubusercontent.com/2605467/148743678-9a671237-31f6-4470-87d7-19f95acb8303.png)

**Comment by karlwilcox** [comment]
This is an Inkscape issue I'm afraid (inkscape does the conversion from SVG to PNG & JPEG). The SVG that DrawShield creates is valid and correct but for Inkscape does not read in the pattern fill correctly, so there's not a lot I can about this in the short term. It may get fixed by Inkscape in the future.

**Comment by karlwilcox** [comment]
Fixed by the new rasterizer
