### ISSUE TITLE
!todo per bend sinister does wrong counterchanged

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#338]
!todo per bend sinister does wrong counterchanged
!draw per bend argent and purpure
  a bend sinister counterchanged

**Comment by ericscheid** [comment]
This `per bend sinister argent and purpure, a bend counterchanged` does this (expected)
![image](https://user-images.githubusercontent.com/2605467/150113610-d28cf7cd-3ca0-4ac0-938d-c0bbfd0e9dcb.png)

but `per bend argent and purpure, a bend sinister counterchanged` does this (wrong)
![image](https://user-images.githubusercontent.com/2605467/150113496-f2079838-b3ac-4506-b6ad-6bb74874a0dd.png)

The `counterchanged` is done across the wrong diagonal.

**Comment by karlwilcox** [comment]
I think #441 has the right solution for this.
