### ISSUE TITLE
!todo nudge positioning of `eagle double headed` to be properly centred

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#342]
!todo nudge positioning of `eagle double headed` to be properly centred
!draw per pale gu az an eagle double headed countercharged

**Comment by ericscheid** [comment]
In this 500px wide image from drawbot, the pale division is at exactly 250px, but the charge does not appear centred — this is most noticeable with the spacing of the necks, but also some fine lines in the tail.

On careful examination, the centre line of the charge is not in the centre. It looks to be about 2 or 3 pixels off. The charge itself is actually centred.

![image](https://user-images.githubusercontent.com/2605467/151288500-93dcb75c-d5e1-45df-b7d1-fa3678068a63.png)

**Comment by ericscheid** [comment]
```
per pale Azure and Vert, 
an eagle double headed Or, 
an eagle double headed Argent reversed
```
The wings are symmetrical, everything else is off-centre.

![image](https://user-images.githubusercontent.com/2605467/151338507-47b65580-f831-424c-9a9a-d8f850ef3a88.png)

**Comment by ericscheid** [comment]
I would think three edits .. 

1. the sinister legs need to be nudged inwards (dexter) by about 3px (note how in the Gules/Argent emblazon the sinister leg is touching the wing feathers),
2. the whole of the tail nudged to dexter by 3px,
3. and the dexter head nudged outwards (to dexter) by 3px.

**Comment by PaoloRuben** [comment]
Since the charge wasn't symmetrical it couldn't poperly be centered, I made two one from each part of the old one.
left:
![Eagle_doubleheaded_sx](https://user-images.githubusercontent.com/57675116/184995552-611d491b-5466-49f4-a9b2-2a57ea11cc8d.svg)
right:
![Eagle_doubleheaded_dx](https://user-images.githubusercontent.com/57675116/184995761-c419f1dd-b0ff-4026-8815-3ad20838f2d0.svg)

**Comment by karlwilcox** [comment]
That’s great thanks! I will upload the new version tonight

**Comment by karlwilcox** [comment]
This is now ready for upload.

**Comment by PaoloRuben** [comment]
I just saw it, dunno why but it shows wrong, it doesn't have some void spaces that it should have and it doesn't sho the eyes as white
