### ISSUE TITLE
!todo make `fillet` be a diminutive `chief` (not a `closet`)

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#379]
!todo make `fillet` be a diminutive `chief` (not a `closet`)

**Comment by ericscheid** [comment]
Discussion here: https://discord.com/channels/775325424854630440/775347423597297704/979168891571945502

1. `fillet` appears as a `closet`
2. Parker notes is sometimes a chief diminutive https://drawshield.net/reference/parker/c/chief.html
3. no mention of a `fillet` on [fess variations](https://drawshield.net/catalog/ordinaries/fess/) or [major ordinaries](https://drawshield.net/catalog/ordinaries/major/) or [minor ordinaries](https://drawshield.net/catalog/ordinaries/minor/)
4. positioning appears off if field is partitioned (argent, a chief or, a fillet vert, a closet gules)
5. exists as adjective for `cross`, `saltire`, and `bordure`

<img width="840" alt="image" src="https://user-images.githubusercontent.com/2605467/170389781-fe8b4f90-3d07-4ba5-9572-c146e48ba67d.png">

![image](https://user-images.githubusercontent.com/2605467/170390166-f48c9517-7124-4a2d-a473-59649c99f22b.png)

**Comment by ericscheid** [comment]
The gallery only has `fillet` with `cross` or `saltire`, no apparent uses as a diminutive `fess` or `chief` (so pretty safe to change)

**Comment by karlwilcox** [comment]
I probably meant to do this in the first place as the closet and fillet are currently completely different ordinaries but visually identical. Need to update the visual catalog.
