### ISSUE TITLE
!todo default tint for stag trippant unguled is Or, should be grey

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#382]
!todo default tint for stag trippant unguled is Or, should be grey

**Comment by ericscheid** [comment]
`!draw sable a stag trippant cendree`

![image](https://user-images.githubusercontent.com/2605467/172319784-66481d49-5a99-4875-83fb-1d878a8af307.png)

`!draw sable a stag trippant cendree unguled gules`
![image](https://user-images.githubusercontent.com/2605467/172319946-3c2de930-885a-4f48-b8d1-75602615ea03.png)
