### ISSUE TITLE
!todo dexter fore hoof of doe-trippant is incompletely tinted

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#383]
!todo dexter fore hoof of doe-trippant is incompletely tinted

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/172319519-6122657b-041f-4990-983e-83a90331cfc0.png)

Hmm, I think that's just the `doe` base. Anyhoo.

**Comment by ericscheid** [comment]
Similar issue with `elk-lodged`, except this time with the sinister fore-hoof

![image](https://user-images.githubusercontent.com/2605467/172321724-f27a8a3f-2430-4091-8c0e-42c41ce7725c.png)

**Comment by ericscheid** [comment]
and `elk-rampant`, partial dexter-fore-hoof

![image](https://user-images.githubusercontent.com/2605467/172322009-9f0b2bba-879b-4a1a-887e-55775cfe9b8b.png)

**Comment by ericscheid** [comment]
very slight incomplete tint of `elk-trippant` dexter fore (zoom in)
![image](https://user-images.githubusercontent.com/2605467/172322355-0d7cae32-3a46-43ae-ae89-480528e36f38.png)

<img width="91" alt="image" src="https://user-images.githubusercontent.com/2605467/172322551-8a1cb9ff-16f1-435d-b4d1-ddf542799b72.png">

**Comment by karlwilcox** [comment]
These are are all done, ready for upload
