### ISSUE TITLE
!todo `stag-springing` and `stag-salient` are undefined

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#384]
!todo `stag-springing` and `stag-salient` are undefined
!draw quarterly
i. argent a doe-rampant grey unguled gules
ii. argent a doe-springing gules unguled vert
iii. argent a doe-salient gules unguled vert
iv. argent

// "Again, instead of the term `rampant`, which is applied to beasts of prey, the terms used for stags are `springing`, or `salient`."

**Comment by ericscheid** [comment]
All three should be in upright posture, only the one using the improper blazon term is properly emblazoned.

![image](https://user-images.githubusercontent.com/2605467/172324555-b9deacc8-f1b3-4d80-940a-26af5bbfda66.png)

**Comment by karlwilcox** [comment]
I've clarified some of these terms so that all game animals, cats, dogs etc. are all "salient" (with "springing" as a synonym) and also added an warning message when rampant is used.
