### ISSUE TITLE
!todo bot is confused with inescutcheon bendy - site is OK

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#385]
!todo bot is confused with inescutcheon bendy - site is OK
https://drawshield.net/cache/8ade3aa5c4551c5d1db5b7619fdca6d2.png

**Comment by ericscheid** [comment]
`!draw Gules, an inescutcheon bendy of 7 Or and Azure`

![image](https://user-images.githubusercontent.com/2605467/172374155-5806531f-7b68-4232-8a34-9d68d62e8f30.png)

**Comment by karlwilcox** [comment]
Bot was using json format, which used the png-old (imagemagick) method of drawing, known to be flaky. I've changed it so it used the 'png' (batik formatter) method. Will be in the next update
