### ISSUE TITLE
!todo bot doesn't understand that default is heater

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#386]
!todo bot doesn't understand that default is heater
> No placement for 12 charges on default, sorry undefined

**Comment by ericscheid** [comment]
default shape for bot is `heater`, but bot doesn't realise that when figuring placement of charges.

needs the shape to be explicit, not default

<img width="426" alt="image" src="https://user-images.githubusercontent.com/2605467/173194146-df1ab12d-dd59-4f11-b06d-174d0c20fb66.png">

**Comment by karlwilcox** [comment]
Fixed by update #387  - Thanks for working this out Eric, this may also fix several other issues where the bot does things incorrectly.
