### ISSUE TITLE
!todo feature request: distribute charges on labels per points

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#389]
!todo feature request: distribute charges on labels per points

**Comment by ericscheid** [comment]
> Thomas, Henry- cousins to the King’s son-did with these forgather: sons were they of the Lord Edmund, late the King’s beloved brother.Earl of Lancaster, was Thomas; these the arms he did advance (not desiring any nobler!): **England with a label France**. Henry, who at all times studied his good father to resemble, bore his brother’s arms with baston azure but without the label.
-- https://www.theheraldrysociety.com/articles/the-siege-of-caerlaverock/

<img width="120" alt="banner of Thomas, Earl of Lancaster" src="https://user-images.githubusercontent.com/2605467/174434693-e4ee180a-d86a-4b52-880e-b528fb7d7302.png">

----

What we got currently is close, but clearly special handling of positioning is needed:

```
!draw Gules,

three lions passant Or in pale 
shown very much closer together

a label entire Azure 
charged with 3 fleur de lys Sable

```
![emblazon showing label charged with 3 fleur de lys](https://user-images.githubusercontent.com/2605467/174434636-36cb05f9-ffd7-4804-bc93-eba0e21b513f.png)

**Comment by ericscheid** [comment]
Oh .. FYI #42 for earlier investigations

**Comment by karlwilcox** [comment]
If there is a single label then it is placed at the top of the shield and made "entire". You can now also things like "a label of 7 points or charged on each point with an ermine spot"
