### ISSUE TITLE
Labels of 4

### ISSUE THREAD

**Issue by PaoloRuben** [drawshield/Drawshield-Code#391]
As for the title it would be great to have a label of 4 for some real world use examples

Arras:

![image](https://user-images.githubusercontent.com/57675116/174476779-144cd8a1-650c-4355-8630-d6ac9ce94a85.png)
HeraldryWiki:
_From : Windhag, Joachim von : Wappen der Erzpatriarche, Kardinäle, Erzbischöfe, Bischöfe, Fürstäbte, Äbte, Pröpste, Orden, Kreuzritter, Äbtissinnen und Frauenklöster in Europa... 16. Jh. Library of University of Tübingen, nr Md 247-4_

Bologna:

![image](https://user-images.githubusercontent.com/57675116/174477057-1e80101c-1535-4432-8653-4bc5aa7e9cb0.png)

**Comment by karlwilcox** [comment]
I've added labels of 4 & 6 that can also be dovetailed or pattee. You can now have labels of from 3 to 7 points
