### ISSUE TITLE
!todo
@​Artifex Scutum can we add a crown like this to drawshield? No idea wh...

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#399]
!todo
@​Artifex Scutum can we add a crown like this to drawshield? No idea what to call it tho… https://en.m.wikipedia.org/wiki/File:%C5%A0iauliai_COA_great.svg

**Comment by karlwilcox** [comment]
Unless someone has a better suggestion we could just call it a Lithuanian crown perhaps?

**Comment by PaoloRuben** [comment]
![Crown](https://user-images.githubusercontent.com/57675116/183909978-a4f7dc4b-b004-47c2-b7d8-ec813fec67db.svg)

Is this good?

**Comment by PaoloRuben** [comment]
to code there are currently 5 pieces that are color: hex ffcc00 (not using the hash for obvious reasons) that can be coloured any colour required similar to how "dukes crown" is treated

**Comment by PaoloRuben** [comment]
![prince-crown](https://user-images.githubusercontent.com/57675116/186773607-fca39580-39ad-4894-b416-cae08592d420.svg)

**Comment by PaoloRuben** [comment]
Ids missing the rest is good
