### ISSUE TITLE
!todo `cat rampant` is emblazoned as `cat winged rampant` (`cat salient` work...

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#402]
!todo `cat rampant` is emblazoned as `cat winged rampant` (`cat salient` works OK)

**Comment by ericscheid** [comment]
`!draw cendree a cat rampant gules`
![cat rampant](https://user-images.githubusercontent.com/2605467/182425731-6da5720f-0dff-4453-a46a-2dfa4647e37e.png)

`!draw cendree a cat winged rampant vert`
![cat winged rampant](https://user-images.githubusercontent.com/2605467/182425909-9e22c9d2-f357-4f12-8670-8f5e28854be2.png)

`!draw cendree a cat salient vert`
![cat salient](https://user-images.githubusercontent.com/2605467/182425688-484ab16c-4faa-4226-82f7-ac7d799f0a7c.png)

**Comment by karlwilcox** [comment]
Sorted, cat rampant now draws an ordinary cat but suggests using salient instead

**Comment by ericscheid** [comment]
Great =)

Note that the [Visual Catalog](https://drawshield.net/catalog/charges/wildlife/) still has it listed as `Cat Rampant`
<img width="240" alt="image" src="https://user-images.githubusercontent.com/2605467/182776543-a3303236-1e2c-41bb-ab98-000f02806db9.png">

As do many other animals. See issue #401
