### ISSUE TITLE
!todo fix serpent in annulo

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#408]
!todo fix serpent in annulo
!draw Vert, a Serpent In Annulo Argent

**Comment by ericscheid** [comment]
![plain old wiggly danger rope](https://user-images.githubusercontent.com/2605467/184287242-8123e4d9-fa40-49d2-90d0-6d14e961af2e.png)

Should be
![nom nom nom serpent in annulo](https://user-images.githubusercontent.com/2605467/184287277-a50b02ad-1818-40a0-a850-a49957415fd7.png)

**Comment by PaoloRuben** [comment]
Dragon in annulo isn't working eihter
