### ISSUE TITLE
More quadrate crosses + fix existing

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#41]
Drawshield's Cross Moline is really a Cross Cercelée (see https://en.wikipedia.org/wiki/Cercelée). Could you change Drawshield's Cross Moline to the one in https://en.wikipedia.org/wiki/Cross_moline ?

Wikipedia has more quadrate crosses than Drawshield I think, are there any others that we can incorporate (and do we really need to pierce, void and fitchy them all...?

**Comment by PaoloRuben** [comment]
![Cross_Moline](https://user-images.githubusercontent.com/57675116/183895768-a3e8e49a-f36d-48d3-9fe0-65f7e567765c.svg)
![Cross_Moline_Pierced](https://user-images.githubusercontent.com/57675116/183895772-3b0faf6d-b5c3-4478-ab4b-e2e9904d80b7.svg)
![Cross_Moline_Voided](https://user-images.githubusercontent.com/57675116/183895775-831f839f-a756-41c9-8721-feb204b955f0.svg)
I made these from an image in the public domain and are free to use.
All .svg

**Comment by PaoloRuben** [comment]
![Cross_Moline_Quadrate](https://user-images.githubusercontent.com/57675116/183896976-5306a150-e019-4714-a382-706b20db6c1d.svg)

**Comment by PaoloRuben** [comment]
![Cross_Moline_Quadrate_Pierced](https://user-images.githubusercontent.com/57675116/183900971-eee5e9e7-0853-4894-844d-fdb625df262f.svg)

**Comment by PaoloRuben** [comment]
![Cross_Moline_Quadrate_Voided](https://user-images.githubusercontent.com/57675116/183900994-9cbb9a57-a676-4ad6-911c-9f5601d3a33b.svg)

Even this maybe?

**Comment by PaoloRuben** [comment]
![Cross_Pattée](https://user-images.githubusercontent.com/57675116/184221995-6a31c57e-85c2-4731-8b79-3916444afc32.svg)

**Comment by PaoloRuben** [comment]
![Cross_Pattée_Pierced](https://user-images.githubusercontent.com/57675116/184222349-c49dd08d-0bd9-45b8-a2b0-8a37caeaee20.svg)

**Comment by karlwilcox** [comment]
I like the ones with a square centre - do we have a proper heraldic name for these?

**Comment by PaoloRuben** [comment]
They're the quadrate crosses

**Comment by PaoloRuben** [comment]
They're named: cross (name of the cross) quadrate

**Comment by PaoloRuben** [comment]
I really don't know if there're any examples of quadrate crosses voided, still I've included one

**Comment by PaoloRuben** [comment]
![Cross_of_Pisa](https://user-images.githubusercontent.com/57675116/187093491-161e4b6c-46cc-4e80-ba83-e46b38f82186.svg)

**Comment by PaoloRuben** [comment]
![Cross_of_Toulouse_filled](https://user-images.githubusercontent.com/57675116/187093793-eaa5d03d-8618-4bfd-8c1c-b559e4ba0a27.svg)

**Comment by PaoloRuben** [comment]
The toulouse one wasn't bad, just it wasn't the same of the voided one

**Comment by PaoloRuben** [comment]
![Cross_sarcelly_voided](https://user-images.githubusercontent.com/57675116/187094255-b668a9be-d607-4743-8f54-4b9d6c16d137.svg)

**Comment by PaoloRuben** [comment]
![Cross_sarcelly_pierced](https://user-images.githubusercontent.com/57675116/187095324-8ef4ee2c-5b99-4e74-9041-e2e11d2e9306.svg)

**Comment by karlwilcox** [comment]
These are all ready
