### ISSUE TITLE
Create Fleur-de-lys-florence

### ISSUE THREAD

**Issue by PaoloRuben** [drawshield/Drawshield-Code#414]
![Fleur_de_lis_of_Florence](https://user-images.githubusercontent.com/57675116/186996322-aa0dcabd-f40b-4767-8a53-2cdcfc098f94.svg)
the SVG is already good

**Comment by PaoloRuben** [comment]
I did it on the base of a copyright free design

**Comment by PaoloRuben** [comment]
another name of it is lily blossomed

**Comment by karlwilcox** [comment]
Great work! Will be in the next update.

**Comment by PaoloRuben** [comment]
It's offset dunno why, I'll check
