### ISSUE TITLE
!todo Better St Mark lion

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#418]
!todo Better St Mark lion

**Comment by PaoloRuben** [comment]
![St  Mark's Lion](https://user-images.githubusercontent.com/57675116/187081418-e538f2bc-3048-484b-847e-f009a8be549f.svg)

**Comment by PaoloRuben** [comment]
ready for upload, I'd say

**Comment by karlwilcox** [comment]
Just doing this one now...

**Comment by karlwilcox** [comment]
Will be uploaded shortly

**Comment by PaoloRuben** [comment]
![St  Mark's Lion with sword](https://user-images.githubusercontent.com/57675116/188513575-aa7233ff-7f74-48ba-8d02-a8b2ca8dcbcf.svg)

**Comment by karlwilcox** [comment]
Beautiful work! I'll upload this tomorrow.
