### ISSUE TITLE
!todo fix gallery search

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#420]
!todo fix gallery search

**Comment by ericscheid** [comment]
The gallery search at https://drawshield.net/gallery/search.html generates search result URLs of the form 

- https://drawshield.net/gallery/000198 

but they need to be of the form 

- https://drawshield.net/gallery/0001/gallery-000198.html

**Comment by karlwilcox** [comment]
Fixed (it was actually the URL rewrites that were broken following the OS upgrade, which had a different security model). This has now been fixed.
