### ISSUE TITLE
!todo Crowns and coronettes rework

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#422]
!todo Crowns and coronettes rework
I have a few requests: 
French shield shape's tip to be much larger
Better French Royal crown, this for example 
A Hungarian royal crown like this
And better arranged multiple quarters on the shield

**Comment by PaoloRuben** [comment]
Both the catalogue and the nomenclature are faulty and there are many requests for new ones. This issue could be merged with #399 
![image](https://user-images.githubusercontent.com/57675116/188311149-3df65440-adcf-4e25-aae6-a53858b09400.png)
![image](https://user-images.githubusercontent.com/57675116/188311157-3a0bf927-1891-41c8-b7d3-6005d4df57c2.png)
these are two suggesions:
French royal crown and
Hungarian Crown

**Comment by PaoloRuben** [comment]
Soon .svg will be available

**Comment by PaoloRuben** [comment]
hungarian crown is nigh impossible to color, we could make it only proper

**Comment by karlwilcox** [comment]
> hungarian crown is nigh impossible to color, we could make it only proper

Yes, that is fine, I think there are others that can only be proper too.

**Comment by PaoloRuben** [comment]
![Crown_of_Hungary](https://user-images.githubusercontent.com/57675116/188510582-e7bf70e4-9253-46be-a0ae-19321fcc147f.svg)
rework from a wikicommons file in the public domain by [Thommy](https://commons.wikimedia.org/wiki/User:Thommy9)

**Comment by PaoloRuben** [comment]
![Royal_Crown_of_France](https://user-images.githubusercontent.com/57675116/189425056-cc91987d-f357-4a16-8b63-70f2f8beda95.svg)
Credits to wikipedia user: Sodacan

**Comment by PaoloRuben** [comment]
if needed I can simplify
