### ISSUE TITLE
!todo  New french shape

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#423]
!todo  New french shape

**Comment by PaoloRuben** [comment]
![French_shield](https://user-images.githubusercontent.com/57675116/188313719-ed36b232-3480-47a8-8ff8-f63ee538eba5.svg)

**Comment by PaoloRuben** [comment]
bordures, tressures and double tressures must be fixed as well given the change in shape.

**Comment by PaoloRuben** [comment]
![Bordure](https://user-images.githubusercontent.com/57675116/189505120-03bf4d97-606a-4210-88f3-8393ef33c984.svg)

**Comment by PaoloRuben** [comment]
![Orle](https://user-images.githubusercontent.com/57675116/189505270-834aa1ff-f4f0-4885-a70a-c33655107983.svg)

**Comment by PaoloRuben** [comment]
![Tressure](https://user-images.githubusercontent.com/57675116/189505581-40edf485-0134-4ee5-ba73-2278cafd8698.svg)
![Double_tressure](https://user-images.githubusercontent.com/57675116/189505583-7fcd8297-3d8f-447f-8cc8-a0a32d089ded.svg)

**Comment by PaoloRuben** [comment]
the double tressure is not quite right, I'llfix it tomorrow

**Comment by PaoloRuben** [comment]
![Tressure](https://user-images.githubusercontent.com/57675116/189551167-8c3ed807-53e0-4ab5-97f2-fea0ea3c5ec6.svg)
Better Tressure
