### ISSUE TITLE
!todo triple moon

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#425]
!todo triple moon

**Comment by PaoloRuben** [comment]
![Triple moon](https://user-images.githubusercontent.com/57675116/188507911-edb2ded4-5ae0-4792-b3fc-c5a895e62a60.svg)

**Comment by PaoloRuben** [comment]
forgot metadata, it's my creation anyway

**Comment by karlwilcox** [comment]
Ready for uploading, I've added your metadata

**Comment by PaoloRuben** [comment]
Thanks, we broke a speed record
