### ISSUE TITLE
!todo Better mullet

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#430]
!todo Better mullet
This type of mullet would be much nicer

**Comment by PaoloRuben** [comment]
![Mullet_of_5_modern](https://user-images.githubusercontent.com/57675116/189494729-cc2744b7-6a1e-4c77-82d6-e6167f95bdb0.svg)
We could mantain both charges by naming this: mullet modern or mullet of 5 modern

**Comment by PaoloRuben** [comment]
Now I see why people think I'm a commie

**Comment by karlwilcox** [comment]
The existing mullet looks slightly odd because it is actually generated "on the fly" and you can have any number of points between 5 and 64(!) The "inner radius" is just guessed.
I have hard-coded the proper calculations for 5 & 6 sides so these both now look "correct" (i.e opposite arms line up properly).
