### ISSUE TITLE
!todo Edge flory

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#431]
!todo Edge flory

**Comment by karlwilcox** [comment]
Can anyone provide an example of how this would look (on a straight edge)?

**Comment by PaoloRuben** [comment]
![Flory](https://user-images.githubusercontent.com/57675116/190228040-557c7c49-2b8a-4c91-8639-91ae6e61d003.png)

**Comment by karlwilcox** [comment]
There is a problem here from confusion with the flory treatment (and presumably there should also a trefly treatment?) might need to use an extra keyword like "a fess gules edged flory"...?

**Comment by karlwilcox** [comment]
The last one is already supported as trefle-counter-trefle but I'll add the alternate construction

**Comment by karlwilcox** [comment]
The last one is already supported as trefle-counter-trefle but I'll add the alternate construction. These are now all done, but I've had to remove "flory" as a synonym for "semy-de-lys" as it was ambiguous
