### ISSUE TITLE
!todo better rainbow

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#435]
!todo better rainbow
We need a way better rainbow http://heraldicart.org/rainbow/rainbow-1-mono.png

**Comment by PaoloRuben** [comment]
![rainbow](https://user-images.githubusercontent.com/57675116/190725712-d0551883-baa0-4892-9889-2d76a3719013.svg)
based on this medieval portrayal of a rainbow 
![image](https://user-images.githubusercontent.com/57675116/190725969-cd1c72e8-d7f9-4832-be11-cecf6657620d.png)
could it be ?

**Comment by PaoloRuben** [comment]
heraldicart

**Comment by karlwilcox** [comment]
This image is used as the "rainbow proper"
