### ISSUE TITLE
!todo alias `griffin's head erased` for `keythong's head erased`

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#437]
!todo alias `griffin's head erased` for `keythong's head erased`
This is `Argent estencely gules, a keythong's head erased and on a chief azure three fleurs-de-lys argent`
However, a full keythong is presented, not the `head erased`. Since a keythong is just a griffin sans wings, the `griffin's head erased` can be effectively substituted.

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/190928734-bdd06b28-2360-482a-a7c3-ad1a56f55df5.png)

<img width="515" alt="image" src="https://user-images.githubusercontent.com/2605467/190928766-7fe4767e-1184-4dfa-8399-5f0e401a0f0f.png">

**Comment by karlwilcox** [comment]
Will do, but see also #438 which needs to be done first
