### ISSUE TITLE
!todo enable `beaked` for `griffin's head erased`

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#438]
!todo enable `beaked` for `griffin's head erased`

**Comment by karlwilcox** [comment]
The current griffin's head erased is from Wikimedia commons but the beak isn't a separate SVG element so can't be coloured. Options are 
a) Adapt the existing one by separating the beak parts
b) Look for a better one on [commons.wi](https://commons.wikimedia.org/w/index.php?search=griffin+svg&title=Special:MediaSearch&go=Go&type=image)
c) Use one of those from http://heraldicart.org/griffin/ (but those are a bit basic)
If we can get a nice one created then we can use it for cooped as well

**Comment by PaoloRuben** [comment]
![Griffin head](https://user-images.githubusercontent.com/57675116/192484553-f57d8584-6bde-4f2f-97f5-68a10eb0abd5.svg)
This is a proposal, it's not exactly right, still I would like some feedback

**Comment by PaoloRuben** [comment]
![Griffin head couped](https://user-images.githubusercontent.com/57675116/192632907-c4bbc77f-bca6-4cef-8736-8459707b1449.svg)

**Comment by PaoloRuben** [comment]
![Griffin head couped](https://user-images.githubusercontent.com/57675116/210769355-69875d86-c1e0-4080-a2a4-207295180d30.svg)
tagged
