### ISSUE TITLE
!todo Better flowers

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#443]
!todo Better flowers
I'll open an issue to upload some better flower charges (mainly I'm trying to clean up some old ones) if you have any suggestions I'll make them

**Comment by PaoloRuben** [comment]
![Trillium](https://user-images.githubusercontent.com/57675116/191734279-89b22535-5c05-4a33-ada2-fc92ee973d46.svg)
This is the same old trillium but now it has specific groups to chang leaved and seeded colors

**Comment by PaoloRuben** [comment]
Proper: Argent leaved vert seeded or.

**Comment by karlwilcox** [comment]
Beautiful, thank you!

**Comment by PaoloRuben** [comment]
![Strawberry](https://user-images.githubusercontent.com/57675116/192395316-940cefa0-3ff5-4d52-b271-c0f349c3837e.svg)
This is done ex novo by me (it took a long time!), as for the trillium it has different groups for seeded and leaved colors.
Proper: Argent leaved vert seeded or.

**Comment by PaoloRuben** [comment]
Hope you like it (feedback very much welcome)

**Comment by PaoloRuben** [comment]
![Strawberry_2](https://user-images.githubusercontent.com/57675116/192396637-415494f8-b377-4a15-80b7-1f912a73a8af.svg)
Alternative

**Comment by PaoloRuben** [comment]
I still see some imperfections I will work on it, if necessary

**Comment by PaoloRuben** [comment]
![Cistus](https://user-images.githubusercontent.com/57675116/192637924-1f1399a8-6b9d-47aa-8460-4a59d2791b1f.svg)
Proper (Argent leaved purpure seeded or)

**Comment by PaoloRuben** [comment]
Design from: https://commons.wikimedia.org/wiki/File:Escudo_de_Anchuras_(Ciudad_Real).svg

**Comment by karlwilcox** [comment]
These are both done and will be uploaded soon
