### ISSUE TITLE
!todo bows (svg already done)

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#452]
!todo bows (svg already done)
I'd love to have different tinctures for arrows, arrow heads and feathers

**Comment by PaoloRuben** [comment]
Since I added way to many parts (kinda) I researched a way to call each part with a proper name; So we have in different groups:

1.  The bow part:

- The main part (in blue "#0000FF") mantaining the colour of the charge
- Handle (in red "#FF0000")
- Stringed (in cyan "#00FFFF") in hindsight I should have used magenta as it's the right secondary or green as it was primary.

2. The arrow part:

- Arrow (in magenta "#FF00FF") If possible the whole group should follow this tinctureif not specified otherwise, even if I know it's a mess.
- Fletched (in yellow "#FFFF00")
- Head (in lime green "#00FF00)

![Bow ](https://user-images.githubusercontent.com/57675116/192887928-4e447dfe-6609-46e5-9f27-43bb86600cf1.svg)
![Bow nocked](https://user-images.githubusercontent.com/57675116/192887934-a34d89b7-c1e0-4687-9865-313f918eac0b.svg)

**Comment by karlwilcox** [comment]
These are great! The final stage is to *name* each of the SVG groups by setting the ID attribute in Inkscape (or whatever you use). Select (or create) a group that contains *only* the particular feature, open the "Object Properties" dialog and change the ID attribute of that group to the name of the feature - See the example in the image attached. That is how the program knows what parts are features and I can just upload the file without any further work.
<img width="950" alt="Screenshot 2022-09-29 at 00 04 35" src="https://user-images.githubusercontent.com/3171760/192904257-358da7f3-3ad9-447c-987c-f3d7cf3798b6.png">

**Comment by PaoloRuben** [comment]
![yes-my-lord-star-wars](https://user-images.githubusercontent.com/57675116/192910395-7f5d482d-2f72-4135-a85c-166cbf8f5eb8.gif)

**Comment by PaoloRuben** [comment]
![it-will-be-done-star-wars](https://user-images.githubusercontent.com/57675116/192910445-60f7952a-1ee3-4253-b9ce-392dc43cd910.gif)
Aw crap! This was way better!

**Comment by PaoloRuben** [comment]
I solved the arrow issue there're now a shaft and an arrow (shaft is bed tho, anyway)

**Comment by PaoloRuben** [comment]
![Bow nocked](https://user-images.githubusercontent.com/57675116/192911508-448f1e43-296a-4fc3-9660-a6c847448875.svg)
This done

**Comment by PaoloRuben** [comment]
![Bow ](https://user-images.githubusercontent.com/57675116/192911717-6a81e9d6-738d-4817-bba0-eb4fc8ef8876.svg)
This too

**Comment by karlwilcox** [comment]
Fantastic! You don't need to make any more changes but just for completeness, if the feature is made up of different parts that you can't group together (e.g. they are in different layers, or some in front and some at the back) then you can just put a dash and a number at the end of the name, so "fletched-1", "fletched-2" etc. (IDs have to be unique within an SVG file, but the program strips off dashes and numbers when it is looking for features).

**Comment by PaoloRuben** [comment]
So... do I have to name the group or the single shapes? I'm sorry today I'm very slow!

**Comment by karlwilcox** [comment]
Sorry didn't mean to confuse! In most cases you can just name the groups like I said in my first post.

Just sometimes there are some awkward situations where you can't put all the parts of a feature in the same group - for example if some parts of feature are behind the body and some are in front you can't group them together as a group can't be in two layers at once. And sometimes it is just easier to have more than one group, like  each of the beaks in the double-headed swan are in their own group, called "beaked-1" and "beaked-2" .

So usually, yes, just name the group after the feature, but if for any reason you need more than one group with the same feature name you can just put numbers after them.

Hope that helps!

**Comment by PaoloRuben** [comment]
Oh yeah, I'm sorry, today is a slow day, got it thanks.
I will check them but I feel like there's no such problem with these two, unlike with the strawberry flower.
Did you check it out? Do you like it? is it to realistic? The petals are somewhat weird.
