### ISSUE TITLE
Owl Displayed Colouring

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#468]
The "Owl Displayed" charge as shown in the visual catalogue seems not to match what is generated when it comes to the "legged" property: In the preview, we have an "owl-displayed grey (legged gules)", where the legs are displayed as gules and the talons are sable.
However, when I create a shield with the same syntax, the talons on the right leg are also coloured gules, whereas the left leg's talons are black. I would much prefer the talons of both feet be the same colour as shown in the catalogue, maybe even with the ability to have them be a different colour than the legs or "armed" as many other avian charges are.

**Comment by PaoloRuben** [comment]
![owl-displayed](https://user-images.githubusercontent.com/57675116/210118244-dad1ba5d-c4fe-46f3-85f6-0c562bbe637b.svg)
