### ISSUE TITLE
!todo better orb

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#476]
!todo better orb
I found a better graphic for the orb charge:
https://commons.m.wikimedia.org/wiki/File:Heraldic_Globus_cruciger.svg

**Comment by PaoloRuben** [comment]
![Globus_cruciger](https://user-images.githubusercontent.com/57675116/210117273-cc383fdc-ba6a-44e8-92c7-e88e3aa41ff3.svg)

**Comment by karlwilcox** [comment]
Done, the detailing can be coloured using the term "garnished"
