### ISSUE TITLE
!todo gallery page with 404 of emblazon

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#478]
!todo gallery page with 404 of emblazon
Gallery Image of the Day: https://drawshield.net/gallery/004146

**Comment by ericscheid** [comment]
Page html has `<img src="img/gallery-2150.png">`

Image is actually located at https://drawshield.net/gallery/0041/img/gallery-004146.png

**Comment by karlwilcox** [comment]
Okay, so that was pretty obscure!

In YAML 1.1, what is the difference between 000077 and 000078?

One of them is a six character string, the other is an Octal number representing 63 in decimal. This was changed in YAML 1.2 but Jekyll (which builds the DrawShield website) still uses 1.1.

Just needed a 9,857 file bulk edit to surround it with quotation marks... I'll upload the fixed files soon.
