### ISSUE TITLE
!todo bugs with charges strongbox, ostrich, mariner's whistle, cranequin

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#479]
!todo bugs with charges strongbox, ostrich, mariner's whistle, cranequin
- `strongbox`  rendering as placeholder
- `ostrich` svg has no tincture regions, ony textures
- `mariner's whistle` is rendering as `mariner's compass`
- `cranequin` is fine, but is not armour — it is part of a crossbow (weapon)
Others from https://discord.com/channels/775325424854630440/775385320496562218/1044747651192737802 appear fine.

**Comment by ericscheid** [comment]
![strongbox](https://user-images.githubusercontent.com/2605467/203474958-b35c8a6d-b0b7-452b-a811-bb5cb0b557d5.png)
![ostrich](https://user-images.githubusercontent.com/2605467/203474999-5494290e-81fc-47a7-ab57-018af66101a2.png)
![mriner's whistle](https://user-images.githubusercontent.com/2605467/203475024-2efe602b-6335-44ff-9ced-46247384b80e.png)
![cranequin](https://user-images.githubusercontent.com/2605467/203475082-f72b3308-9d7e-4531-b5ed-d6369e43fd0b.png)

**Comment by karlwilcox** [comment]
All fixed, to be in the next release
