### ISSUE TITLE
clicking the image for Hatching palette selects Flat palette

### ISSUE THREAD

**Issue by ericscheid** [drawshield/Drawshield-Code#482]
<img width="699" alt="image" src="https://user-images.githubusercontent.com/2605467/205429091-1f2583a1-f3c7-480d-af58-3955315d4b1b.png">

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/2605467/205429153-b4bbc933-6c09-409f-a7a3-988576161d21.png">

The `onclick` handler for the Hatching image references `#palette6`, which is the `id` for the Flat palette. (Also, the `id` for the "hatching" radio button has the same `id` as the radio button for "flat", which explains how this bug came to be.)

**Comment by karlwilcox** [comment]
Don't know where that sneaked in from...
 Will upload fixed version soon, well spotted!
