### ISSUE TITLE
!todo hatching palette is broken (bot and web)

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#483]
!todo hatching palette is broken (bot and web)
Not able to process: with hatching palette  (4:25-4:45) undefined

**Comment by ericscheid** [comment]
<img width="893" alt="image" src="https://user-images.githubusercontent.com/2605467/205429465-f8610e98-a524-4fc4-8174-ee52caa8aedf.png">

<img width="824" alt="image" src="https://user-images.githubusercontent.com/2605467/205429732-18c1b724-5762-4122-bc56-db55d05d85a2.png">

## Used to work:
<img width="639" alt="image" src="https://user-images.githubusercontent.com/2605467/205429531-599581fb-a5bc-48c1-b583-0de4471f3588.png">
