### ISSUE TITLE
Discord Gallery Bot needs update to fit with fix of #478

### ISSUE THREAD

**Issue by ericscheid** [drawshield/Drawshield-Code#485]
#478
> Okay, so that was pretty obscure!
> In YAML 1.1 [obscure]

Yup

> Just needed a 9,857 file bulk edit to surround it with quotation marks... I'll upload the fixed files soon.

The fix for #478 created a new bug - the Gallery Bot hasn't been told to ignore the quotes and is messing up the URLs

<img width="826" alt="image" src="https://user-images.githubusercontent.com/2605467/206684476-8c99d869-ab3f-43d5-b704-fe8c1127c3aa.png">

**Comment by karlwilcox** [comment]
Thanks, I'll check this. Probably also a good time to move the gallery search back on to the server as the index is now getting too big to load locally.

**Comment by karlwilcox** [comment]
The gallery bot is fixed.

**Comment by karlwilcox** [comment]
And I’m working on a new gallery search page.
