### ISSUE TITLE
!todo taller and shorter artist hints have no effect on charges placed into regions of the field

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#488]
!todo taller and shorter artist hints have no effect on charges placed into regions of the field
!draw cendree,
in dexter side a lion rampant az shown much taller;
in sinister side a lion rampant gu shown much shorter;

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/208018946-8f3b4831-2983-4418-a821-0ec914be82c2.png)

**Comment by ericscheid** [comment]
Furthermore, leaving out the `;` after the first charge causes the parser to choke on the rest of the blazon

<img width="755" alt="image" src="https://user-images.githubusercontent.com/2605467/208019196-e4a311dd-5818-4953-be32-b500cd1d6d9f.png">
