### ISSUE TITLE
!todo 'wider' artist hint for charge placed in region is larger, not wider

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#489]
!todo 'wider' artist hint for charge placed in region is larger, not wider
!draw cendree,
in dexter side a lion rampant vert shown much wider;
in sinister side a lion rampant gu

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/208020103-abfd0dd4-481f-4d12-9025-6bc3aea22ecc.png)

**Comment by ericscheid** [comment]
Compare 
<img width="490" alt="image" src="https://user-images.githubusercontent.com/2605467/208020163-b581b293-2214-426b-bb8d-14a6f044744d.png">

**Comment by ericscheid** [comment]
Also, similarly, `narrower` simply shrinks the charge.
<img width="491" alt="image" src="https://user-images.githubusercontent.com/2605467/208020453-d49b0d45-38c9-427b-964f-ed5dfe3cd1f6.png">

**Comment by karlwilcox** [comment]
Fixed with #488
