### ISSUE TITLE
!todo Suggestion: parse pairs of `~~` as signifying comment markers

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#490]
!todo Suggestion: parse pairs of `~~` as signifying comment markers
!draw arg a bend gu ~~4 bezants~~

**Comment by ericscheid** [comment]
The original blazon as submitted to drawbot being `!draw arg a bend gu ~~4 bezants~~`

So, equivalent to `!draw arg a bend gu (4 bezants)`
