### ISSUE TITLE
!todo geometry of `per bend sinister indented` is wrong

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#493]
!todo geometry of `per bend sinister indented` is wrong

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/208219783-83d0d540-32ed-40a1-bafe-1848c293360c.png)

**Comment by ericscheid** [comment]
A plain `bend sinister indented` is fine, it's just the `per bend sinister` that is bork.

**Comment by karlwilcox** [comment]
Might be related to #441?
