### ISSUE TITLE
!todo `<animal> gorged with a <headwear>`

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#494]
!todo `<animal> gorged with a <headwear>`

**Comment by ericscheid** [comment]
Suggestion to add `<animal> gorged with a <headwear>`, though I do understand that this would require adding positioning metadata to all animals. This would be similar to what would be needed to add `<animal> crowned with a <headwear>` also. Note that some animals might have parts that could clip the headwear (like that griffin's wing, below). 

![image](https://user-images.githubusercontent.com/2605467/208246234-88ec52f7-7a13-41f6-8036-508bf44a5c6c.png)

![image](https://user-images.githubusercontent.com/2605467/208246216-3fd27b3a-ed03-43c1-a3a0-1abd8d688dbf.png)

Wikipedia attests to the practice (https://en.wikipedia.org/wiki/Crown_(heraldry)#As_a_charge).

**Comment by karlwilcox** [comment]
This was already partially implemented but no animals have been marked up. I've finished the code and just marked up the basic 'lion' as an example.

**Comment by ericscheid** [comment]
I could assist with a "pin the tail on the donkey" UI thing to assist with crowd sourcing the needed metadata (for `crowned`, `gorged`, `holding`, etc[?])

**Comment by karlwilcox** [comment]
I'll try to record a video showing how its done...
