### ISSUE TITLE
!todo `bend sinister counterchanged` is invisible

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#495]
!todo `bend sinister counterchanged` is invisible
!draw per pale argent and sable, 
a bend couped countercharged
a bend sinister couped countercharged

**Comment by ericscheid** [comment]
the `bend sinister` is actually there, it's just not visible because the `sinister` transformation is being applied _after_ the `counterchanged` transformation.

<img width="383" alt="image" src="https://user-images.githubusercontent.com/2605467/208251919-529128cc-3275-4b41-8e12-7ea3af9f54b0.png">

**Comment by karlwilcox** [comment]
See also #244

**Comment by karlwilcox** [comment]
Fixed by #441
