### ISSUE TITLE
!todo suggestions: two synonyms; parsing precision tweak

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#496]
!todo suggestions: two synonyms; parsing precision tweak
> Argent a two-headed eagle displayed Sable; on a chief Vert two spur rowels Or.

Suggestions:
1. add `two-headed eagle` as synonym for `double-headed eagle`
2. add `spur rowels` as synonym for `mullet pierced` (not technically a synonym)
3. use `;` to prevent `on a chief` getting assigned to the prior phrase

**Comment by ericscheid** [comment]
image from AmericanHeraldry.org.

![image](https://user-images.githubusercontent.com/2605467/208252949-22517ce6-325d-4399-90f7-8061fed0d626.png)

(the drawshield attempt at this tastes of sadness and despair)

**Comment by ericscheid** [comment]
A correction:

> The term **Spur-rowel** is sometimes used in modern heraldry to signify a **[mullet](https://drawshield.net/reference/parker/m/mullet.html), of six points, pierced.**
See old fr. rouwel, &c., under [Rowel](https://drawshield.net/reference/parker/r/rowel.html).

NB. drawshield doesn't recognise `a mullet of six points`, it has to be `a mullet of six`.

**Comment by karlwilcox** [comment]
All done.
