### ISSUE TITLE
!todo dumbify smart possessive apostrophes

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#498]
!todo dumbify smart possessive apostrophes
!draw Per chevron Gules and Ermine in chief two lions’ heads erased Or.

**Comment by ericscheid** [comment]
<img width="745" alt="image" src="https://user-images.githubusercontent.com/2605467/208271673-19de2a3d-f7a2-4278-b038-0966fc220318.png">

**Comment by karlwilcox** [comment]
This is done, to make things easier I've implemented the rule that single quotes are ALWAYS apostrophes - if you want to mark a string you _must_ use double quotes
