### ISSUE TITLE
!todo fix `falcon` svg

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#500]
!todo fix `falcon` svg
!draw cendree 11 falcons gu // svg has floating splotch

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/208283770-68402622-7db9-414e-9292-8c6326bb49d7.png)

Splotch is upward and leftward (dexter) of charge .. far enough to not actually be in field if only 1 charge.
<img width="472" alt="image" src="https://user-images.githubusercontent.com/2605467/208283872-49e7fade-9154-4978-94a3-d0d359895d1f.png">
