### ISSUE TITLE
!todo add `tressure flory` (not double/counter)

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#501]
!todo add `tressure flory` (not double/counter)
`a tressure flory` -- one sided, unlike `tressure flory counter flory` (Atkins, Joseph of Newburyport, Mass., 1728)

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/208293882-6ca2e753-157b-401e-a6a4-11bbb8ad9990.png)

Also https://en.wikipedia.org/wiki/Sir_William_Gladstone,_7th_Baronet
