### ISSUE TITLE
!todo
`drawn on a <whatever> shape`  isn't working, is throwing a parsing error

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#502]
!todo
`drawn on a <whatever> shape`  isn't working, is throwing a parsing error

**Comment by ericscheid** [comment]
Testing .. is just three shapes not working (lozenge, oval, square):
<img width="443" alt="image" src="https://user-images.githubusercontent.com/2605467/208323154-8f0a792a-a010-414c-ab2d-1804843af96b.png">
