### ISSUE TITLE
!todo some shields have wrong `alt` text

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#504]
!todo some shields have wrong `alt` text
Selecting all the shield types in the web and then copy/pasting reveals a minor bug — three have the wrong `alt` text
> 
> Heater
> heater
> 
> French
> french
> 
> [...]
> 
> SCA
> sca
> 
> Hungarian
> sca
> 
> Scutum
> sca
> 
> Swatch
> sca
> 
> [..]

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/208326227-f16a6647-59de-4b24-ac80-ad18c760c91e.png)
![image](https://user-images.githubusercontent.com/2605467/208326234-e48a931a-13d0-4b1b-a641-a686ce62d26f.png)
