### ISSUE TITLE
!todo `fireball` options

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#505]
!todo `fireball` options
Suggestions for `fireball` charge
1. enable adding tincture for the flames by the modifier `fired <tincture>`
2. `proper` tincture = some combo of Gules, Orange, Or

**Comment by ericscheid** [comment]
`three fireballs Sable fired Proper`

![image](https://user-images.githubusercontent.com/2605467/208425226-8f080e37-df11-4f4e-afdd-e3abb08834a6.png)

**Comment by karlwilcox** [comment]
Done, but features (like "fired") can only be a single colour so it ain't as pretty as that one.

**Comment by ericscheid** [comment]
So `proper` can't be done as multi-colored?

**Comment by karlwilcox** [comment]
Good point, although the way things work the body has to be a fixed colour too (so probably black). I'll do this soon.
