### ISSUE TITLE
!todo parse `contourne` as `reversed` (not `reguardant`). Also synonym add `c...

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#507]
!todo parse `contourne` as `reversed` (not `reguardant`). Also synonym add `contourney`.

**Comment by ericscheid** [comment]
From Elvin's ..

12. [Ar. on a mount vert, a lion ramp. contourne gu. supporting an orange tree-fructed ppr. De la Motte](https://drawshield.net/reference/elvin/plate22.html)

and 

18. [Lion Sejant Contourne](https://drawshield.net/reference/elvin/plate26.html)
 
![image](https://user-images.githubusercontent.com/2605467/208585586-ca4541ee-543a-4925-92fd-634f91f615ce.png)
![image](https://user-images.githubusercontent.com/2605467/208585596-f5728261-e60d-439e-8717-1a2ccbc3a8f0.png)

**Comment by ericscheid** [comment]
Correction: `contourny` as synonym 

(but also `contourney` as a spelling correction synonym)
(and also `contourned`)


----
Footnote offering sources in sense of sharing

- 17 blazons in [AmericanHeraldry.org](https://www.americanheraldry.org/heraldry-in-the-usa/roll-of-early-american-arms/)
- https://www.wikidata.org/wiki/Q56854766
- https://en.wikipedia.org/wiki/Charge_(heraldry)#Attitude_of_animals
- https://en.wikipedia.org/wiki/Attitude_(heraldry)#Positions_indicating_direction
