### ISSUE TITLE
!todo `<some-charge-clause> all within a bordure`  has `bordure` applied to the `<charge>`

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#509]
!todo `<some-charge-clause> all within a bordure`  has `bordure` applied to the `<charge>`
!draw Azure three dolphins Argent all within a bordure engrailed Gules
// This one is weird .. note how the bordure has been applied to the dolphins

**Comment by ericscheid** [comment]
Avoiding the `all within` syntax has things behave correctly.

See also https://github.com/drawshield/Drawshield-Code/issues/86

<img width="544" alt="image" src="https://user-images.githubusercontent.com/2605467/208590981-b2546212-0f5d-46ff-93d5-745e7fb1573e.png">
