### ISSUE TITLE
Portuguese armillary sphere

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#516]
Contact Form: Message: Please add the charge "Portuguese Armillary Sphere" as seen on this site:
https://openclipart.org/download/248986/ArmillarySphere.svg

(I get an error message about an expired cert so I'm not looking at this until it is fixed - I need the SVG file and the author so I can appropriate credit)

**Comment by PaoloRuben** [comment]
The file is a creative commons: https://openclipart.org/detail/248986/armillary-sphere

**Comment by PaoloRuben** [comment]
![Armillary sphere](https://user-images.githubusercontent.com/57675116/210117788-73c2fa29-ac0c-4fed-8653-32b9477ae4aa.svg)

**Comment by PaoloRuben** [comment]
https://openclipart.org/may-clipart-be-used-comparison
