### ISSUE TITLE
!todo resize `paly` when quartered to fit the quarter

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#517]
!todo resize `paly` when quartered to fit the quarter
Specifically targeting quarters would appear to explicitly establish the size of the region and so the default paly of 8 is fully visible. Meanwhile, when not explicitly targeting particular regions the paly of 8 is sized for the full field (but only visible for half-width, thus paly of 4). Maybe. I'm guessing.

**Comment by ericscheid** [comment]
Compare:

1. `quarterly, azure and paly gules and sable`
2. `quarterly, first and fourth quarter azure; second and third quarter paly gules and sable`
3. `quarterly, azure and paly of 7 gules and sable`
4. `quarterly, azure and paly of 5 gules, sable, or, argent, and orange`

<img width="416" alt="image" src="https://user-images.githubusercontent.com/2605467/209140051-15471ec6-d062-4c4a-bfd2-aade269ee92c.png">

<img width="406" alt="image" src="https://user-images.githubusercontent.com/2605467/209139978-ef58ce36-38fc-4564-a6c5-cc43f255abac.png">

<img width="503" alt="image" src="https://user-images.githubusercontent.com/2605467/209139907-57c1f9cc-b593-4f64-b1bd-9f3b7ba2d857.png">

<img width="605" alt="image" src="https://user-images.githubusercontent.com/2605467/209140792-71405194-22e0-4a90-a309-ecb1f1a91a38.png">

**Comment by karlwilcox** [comment]
On reflection I think this is the correct behaviour. Quarterly is a division which shows two different tinctures (like per pale), those tinctures should not be adjusted to fit. Quartered is explicitly a combination of 4 (or more) separate shields, scaled to fit. I think it is best to have this flexibility rather than forcing quarterly to work like quartered.
