### ISSUE TITLE
!todo dragon improvements

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#529]
!todo dragon improvements
- "Dormant" and "sejant affronty" have the same uncolored bands of scales, while the other attitudes color those scales the same as the rest of the body
- Every currently-available attitude except "passant" also leaves the wing structure uncolored, although "passant" and "rampant" will accept "winged" despite the catalog not listing that

**Comment by karlwilcox** [comment]
Following from this, would it help to point out individual instances as they're found? For example, "dragon displayed" both has an obvious tongue yet can't accept "langued" and has very visible bands of scales that can't be tinctured by any means

**Comment by PaoloRuben** [comment]
![dragon-displayed](https://user-images.githubusercontent.com/57675116/210116723-4afa923f-20e9-4a76-86b5-3290b34dc0ae.svg)

**Comment by karlwilcox** [comment]
Beuatiful. thank you!

**Comment by PaoloRuben** [comment]
more to come
