### ISSUE TITLE
!todo fix `cross humetty` synonym to be `cross couped`

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#530]
!todo fix `cross humetty` synonym to be `cross couped`
!draw a roll of 3 columns
Cendree, a cross couped Vert
then
Cendree, a cross humetty Gules // this is wrong
then
Cendree, a greek cross Vert
// Parker and Elvin both term a `cross` that has been `couped` a `cross humetty`
// Elvin defines a `Greek Cross` as only "Has its four limbs all of equal length" (which is vague)
// Neither Parker or Elvin appear to have illustrations for `greek cross`

**Comment by ericscheid** [comment]
Left to right: 
1. `a cross couped`
2. `a cross humetty`
3. `a Greek cross`

![image](https://user-images.githubusercontent.com/2605467/209943676-d0e6cae0-4c34-4247-80b4-2fce509f49fc.png)

Elvin, plate 8 fig. 28: `Cross couped humette, or humetty`
<img width="169" alt="image" src="https://user-images.githubusercontent.com/2605467/209943125-49076dcc-5a6c-4dd0-a8e2-783b3d75e9dd.png">

Elvin, plate 9 fig. 18: `Cross Couped fleury,or Humetty flurty or florette`
<img width="175" alt="image" src="https://user-images.githubusercontent.com/2605467/209943315-a46ae384-c854-4a68-bbd9-4faf09f60774.png">

Elvin: `Humettee`
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/2605467/209943508-7a8e286b-547e-48a7-bd0d-96153c0f0aef.png">

Parker: `cross couped`
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/2605467/209947847-908f6123-ba21-467b-bdc4-c2838dfccf1f.png">

**Comment by karlwilcox** [comment]
Fixed the hummetty error. I think you are right, there isn't a separate "Greek Cross", it is just a Cross Couped according to the discussion here https://commons.wikimedia.org/wiki/File:Royal_Arms_of_Greece_(blue_cross).svg, I'll remove it as it just causes confusion.
