### ISSUE TITLE
!todo `cross-flory-lozenge` (and variants) not parsing right

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#534]
!todo `cross-flory-lozenge` (and variants) not parsing right

**Comment by ericscheid** [comment]
An error recognising three variants of cross-flory-lozenge. Also in newly generated catalog page.

<img width="773" alt="image" src="https://user-images.githubusercontent.com/2605467/210087356-ffc8f407-c2ce-4e87-9271-1b7ffe64bf4c.png">

<img width="330" alt="image" src="https://user-images.githubusercontent.com/2605467/210087337-a4434412-3d47-4c7c-bc7f-c373dcaae4c6.png">

**Comment by karlwilcox** [comment]
This is a naming problem, it should really be "a cross flory of 1 lozenge", I've updated this. (They are quite ugly anyway!)
