### ISSUE TITLE
!todo `cross-gammedion-clubbed` not recognised

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#535]
!todo `cross-gammedion-clubbed` not recognised

**Comment by ericscheid** [comment]
Renders as plain `cross-gammedion` (no clubbing).

Also note doubling of "clubbed" (and similar with `Fitchy`, `Pierced`, `Voided`, although those 3 do render the variants).

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/2605467/210088372-4283a9cc-034d-4331-aaea-9197910e7269.png">

<img width="637" alt="image" src="https://user-images.githubusercontent.com/2605467/210088257-97a9de52-0858-44d3-979f-1a569910e5f7.png">
