### ISSUE TITLE
!todo `cross sarcelly` is off centre

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#536]
!todo `cross sarcelly` is off centre
!draw Argent a cross sarcelly pierced Gules a grid Sable // piercing is not off centre .. the cross sarcelly is raised

**Comment by ericscheid** [comment]
This for each of the `cross-sarcelly` variants, and obviously noticeable with `pierced` and `voided` (where the piercing and voiding is on-centre).

<img width="432" alt="image" src="https://user-images.githubusercontent.com/2605467/210091642-e1c8b237-33b3-4150-92bc-289ab2a2a0cd.png">

**Comment by PaoloRuben** [comment]
![Cross_sarcelly_pierced](https://user-images.githubusercontent.com/57675116/210115892-e8f82a59-ccc6-40b6-9e78-13eb7294e52f.svg)
![Cross_sarcelly_voided](https://user-images.githubusercontent.com/57675116/210115895-76ddc0f7-2587-417a-9ca3-2615fbfdd1e3.svg)

**Comment by karlwilcox** [comment]
Thanks, will upload these tonight

**Comment by ericscheid** [comment]
Confirming fixed for `cross sarcelly`, `cross sarcelly pierced`, and `cross sarcelly voided`.
However, `cross sarcelly fitchy` is still off-centre (and also off-sized).

![image](https://user-images.githubusercontent.com/2605467/210128791-97794f23-079a-4eac-8a39-36fad344415d.png)
