### ISSUE TITLE
!todo `cross gammadion clubbed` is not clubbed

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#537]
!todo `cross gammadion clubbed` is not clubbed
!draw a roll of 2 columns
Argent, a Cross Gammadion Clubbed Gules // is not clubbed
then 
Argent, a Fylfot Clubbed Vert // is clubbed, and Fylfot is synonym for Cross Gammadion

**Comment by ericscheid** [comment]
Compare with `Fylfot Clubbed`

Top row are `Cross Gammedions`, bottom row are `Fylfots`:
![image](https://user-images.githubusercontent.com/2605467/210096600-4302e7c8-724e-4f90-aead-17a19f3d5056.png)

(Also, now I put them into a roll, I see they are not synonyms. Learn something everyday.)

**Comment by karlwilcox** [comment]
The modifier "clubbed" was missing, now added.
