### ISSUE TITLE
!todo `cross recercele fitchy` — should it even exist?

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#540]
!todo `cross recercele fitchy` — should it even exist?
!draw Argent, a cross recercele fitchy Gules

**Comment by ericscheid** [comment]
`fitchy` of a cross means to make the base leg of the crosss pointed, such that it can be staked into the ground.

The basic form and structure of `cross recercele` would suggest that it isn't even possible for that particular cross.

DS currently draws `cross recercele` and `cross recercele fitchy` exactly the same and without parser complaint (e.g. "blah blah may not be blah"). The catalog has both terms on the symmetrical crosses page, both drawn the same (of course).
<img width="417" alt="image" src="https://user-images.githubusercontent.com/2605467/210122179-d3136606-287b-4b47-b4c8-ae05c8c3b9f3.png">


There is no mention of `cross recercele fitchy` in the gallery, nor in Parker or Elvin.

Remove it entirely?

<img width="355" alt="image" src="https://user-images.githubusercontent.com/2605467/210121693-2e5d6d26-0b8c-4f02-a45e-88021b13bbaa.png">

**Comment by karlwilcox** [comment]
You are right, this doesn't make sense, I have removed it.
