### ISSUE TITLE
!todo `crosslet-paty-fitchy` is `fitchy at the foot`

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#541]
!todo `crosslet-paty-fitchy` is `fitchy at the foot`
!draw Argent a crosslet-paty-fitchy Gules
// this looks more like `fitchy at the foot`
// https://mistholme.com/dictionary/cross-fitchy-fitched-fitched-foot/

**Comment by ericscheid** [comment]
Make crosslet-paty-fitchy consistent with other crosses-fitchy (ie. bottom leg made into spike, not a point issuant from bottom leg).

L-R: drawshield render, fitchy, fitchy at the foot

<img width="150" alt="drawshield render" src="https://user-images.githubusercontent.com/2605467/210122774-ad21e42b-4d77-4e95-8261-edbad25cacf6.png"><img width="150" alt="fitchy" src="https://user-images.githubusercontent.com/2605467/210122778-97252018-bc68-4cd1-9f2f-abc9451f4bb0.png"><img width="150" alt="fitchy at the foot" src="https://user-images.githubusercontent.com/2605467/210122782-69ba3fb4-910a-40ea-8cb5-5e16739bd25b.png">

**Comment by karlwilcox** [comment]
The crosslet paty (also known as formy) now has the three variants.
