### ISSUE TITLE
!todo `cross couped` is not centred on the field

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#542]
!todo `cross couped` is not centred on the field
!draw quarterly Or and Argent, a cross couped Gules

**Comment by ericscheid** [comment]
Both `cross couped` and `cross couped voided` are off centre.

All the other cross charges are centred on the field.

<img width="402" alt="image" src="https://user-images.githubusercontent.com/2605467/210128149-b55397ec-0c72-490f-9bab-dcff9fe255c4.png">

![image](https://user-images.githubusercontent.com/2605467/210129160-27b0a194-b407-4300-b47b-23df94b31039.png)

**Comment by karlwilcox** [comment]
This is done, and I've written the code to make it easy to add any other crosses that should follow the same logic.

**Comment by karlwilcox** [comment]
I've added the saltire couped and the cross calatrava, which I think are the only crosses to add. If there are any other charges please let me know.
