### ISSUE TITLE
!todo Log (completed)

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#545]
!todo Log (completed)

**Comment by PaoloRuben** [comment]
![log](https://user-images.githubusercontent.com/57675116/210642643-9e493d74-6500-454d-ba39-cb62b4ae3e48.svg)

**Comment by PaoloRuben** [comment]
![log](https://user-images.githubusercontent.com/57675116/210643216-45a5f2bd-600f-4634-ab46-1e9719f3f93c.svg)
Metadata was missing
