### ISSUE TITLE
!todo fix new charges

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#547]
!todo fix new charges

**Comment by PaoloRuben** [comment]
Many of the new charges have some problems, here's a list:
**Missing**:
bird-foot 
duck-foot 
heron-volant 
heron-wings-displayed
dragon-head-cabossed 
eagle-foot
hawk-rising
basilisk 
walleye 
**Naming issues**:
dragon-wingless-couchant
calamarie-embowed 
**Colouring issues**:
robin
dragon
killer-whale
eagle
eagle-striking

**Comment by karlwilcox** [comment]
Missing: All fixed
bird-foot 
duck-foot
heron-volant
heron-wings-displayed
dragon-head-cabossed
eagle-foot
hawk-rising
basilisk
walleye
Naming issues:
dragon-wingless-couchant (What is the problem here?)
calamarie-embowed (And here?)
Colouring issues: Fixed
robin
dragon (being dealt with separately)
killer-whale
eagle (intentional)
eagle-striking (intentional)

**Comment by ericscheid** [comment]
Don't know about "naming issues", but dragon-wingless-couchant has extraneous dots

<img width="675" alt="image" src="https://user-images.githubusercontent.com/2605467/211125452-a7985105-65ee-4914-b710-d49c8b178ece.png">

**Comment by ericscheid** [comment]
Also, what's the natural reference for `hawk-rising-one-leg-raised`, because just using the svg file name doesn't work quite right:

<img width="507" alt="image" src="https://user-images.githubusercontent.com/2605467/211125742-d2b7fe78-7465-498a-86e9-802fbc4da6e4.png">

**Comment by PaoloRuben** [comment]
Yeah, I messed up, dragon couchant is the dots, calamari e is the fact that  the charge appears the same as embowed and not embowed

**Comment by ericscheid** [comment]
As for default `baslisk` .. it is rendering as `basilisk-wings-displayed` when blazoned as simply `basilisk`.
Heraldicart has no plain basilisk image, just the four postured variants.
 
The question then is "Is that the correct _default_ posture?"

Swinton and Pendlebury Council has the blazon "a cockatrice Or" as `basilisk-sejant`
https://commons.wikimedia.org/wiki/File:Str%C3%B6hl_Heraldischer_Atlas_t30_2.jpg

Ströhl Heraldischer Atlas t30 2 has the charge as `basilisk-wings-displayed`, but I don't see what the blazon is.
https://commons.wikimedia.org/wiki/File:Swinton_and_Pendlebury_Council_-_coat_of_arms.PNG

Erb Vraždů z Kunvaldu has the charge as `sejant`
https://commons.wikimedia.org/wiki/File:Erb_Vra%C5%BEd%C5%AF_z_Kunvaldu.png

.. and most modern emblazons render the charge as `sejant`.
https://commons.wikimedia.org/wiki/Category:Basilisk_in_heraldry

The town of Sankt Johann does have it as `wings-displayed`, 
https://de.wikipedia.org/wiki/Sankt_Johann_(bei_Mayen)#Wappen
.. however, the arms of the Breidbach family (upon which the town's arms derive) has it as `sejant`
https://de.wikipedia.org/wiki/Breidbach_(Adelsgeschlecht)#Wappen

**Suggestion: make `basilisk` the same rendering as `basilisk-sejant`.**

**Comment by karlwilcox** [comment]
All done
