### ISSUE TITLE
!todo web: fix `onchange` for Use Dev Vesion

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#550]
!todo web: fix `onchange` for Use Dev Vesion
The `onchange` attribute of the "Use Development Version" checkbox in preferences has a bad reference.

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/211226158-69ebb60c-3491-4b88-abbd-cbc062088c5e.png)

**Comment by karlwilcox** [comment]
This was just for persisting the setting between settings, but is now fixed
