### ISSUE TITLE
!todo `arm-habited` and `man-armoured` have outline strokes

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#551]
!todo `arm-habited` and `man-armoured` have outline strokes

**Comment by ericscheid** [comment]
<img width="579" alt="image" src="https://user-images.githubusercontent.com/2605467/211451211-9602b1fc-862b-4d97-a9f4-382dc02ab1f3.png">

<img width="585" alt="image" src="https://user-images.githubusercontent.com/2605467/211451245-cb43f650-5676-4214-a3fd-f1d2a4984a05.png">

**Comment by karlwilcox** [comment]
These two are now fixed. The double stroke thing is how they arrived from Heraldic art - they can be a bit fiddly to fix (need tweaking in Inkscape) so please report them but from now on I'll just label them as "Atrifacts" and probably not work on them myself.
