### ISSUE TITLE
!todo `house` chimney is uncoloured

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#552]
!todo `house` chimney is uncoloured
!test Argent, a house Gules // is the chimney meant to be uncoloured?

**Comment by ericscheid** [comment]
<img width="615" alt="image" src="https://user-images.githubusercontent.com/2605467/211451421-6528e94f-b6b1-48ab-9051-20c55ff50ea3.png">

**Comment by karlwilcox** [comment]
Done, you can also now change the colour of the roof.
