### ISSUE TITLE
!todo `a palette` charge parsing error

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#553]
!todo `a palette` charge parsing error
!test Argent, a palette Gules // something really not working .. namespace collision with the `drawn with` directive?

**Comment by ericscheid** [comment]
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/2605467/211451663-2d779ee0-9b0f-4838-8590-30f8cc2cf659.png">

**Comment by karlwilcox** [comment]
Well spotted, it is probably easiest to just require the charge to be called an "artist palette".
