### ISSUE TITLE
!todo Fix stars and estoiles

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#554]
!todo Fix stars and estoiles
https://drawshield.net/cache/199b204dcd340f48521113facdb024a0.png

**Comment by PaoloRuben** [comment]
Drawshields in theory has a line of code for distinguishing different stars, it doesn't seem to work. Furthermore:
- The art of **estoile** has to be tweaked
-  **star of 6** and **star of 8** are estoiles (we should add estoiles of 6 and 8 and have new art for star of 6 and 8)
- we could probably add pierced stars (maybe?)

**Comment by karlwilcox** [comment]
I think these are done
