### ISSUE TITLE
!todo remove yellow tail lion

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#555]
!todo remove yellow tail lion

**Comment by PaoloRuben** [comment]
![lion-rampant](https://user-images.githubusercontent.com/57675116/212409088-49b6d21f-1a8b-4755-8768-267ae0075971.svg)

**Comment by PaoloRuben** [comment]
![a lion rampant nowed](https://user-images.githubusercontent.com/57675116/212477758-875dc95c-f4bf-4ba5-9684-480987924d4e.svg)

**Comment by PaoloRuben** [comment]
- Rampant
- Rampant nowed

**Comment by PaoloRuben** [comment]
![lion cadent](https://user-images.githubusercontent.com/57675116/212539683-edfe637a-4e8e-4905-a6cc-1569c705d8c0.svg)

- Cadent

**Comment by PaoloRuben** [comment]
![lion-rampant-reguardant](https://user-images.githubusercontent.com/57675116/212539974-c447cf40-e07d-4b69-8ae8-1d81c2e6895b.svg)

- Rampant reguardant
