### ISSUE TITLE
!todo arrangements and proper not working together

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#556]
!todo arrangements and proper not working together
https://drawshield.net/cache/4dbcac38bc863e7d3feaf6f1130ce583.png

**Comment by PaoloRuben** [comment]
!test Argent 3 roses in pale azure leaved proper and seeded proper

**Comment by PaoloRuben** [comment]
opshtray — Oggi alle 21:28
has nothing to do with arrangements
just number of charges > 1

**Comment by PaoloRuben** [comment]
and only with proper features
