### ISSUE TITLE
Position of charges in orle (and on Bordure)

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#56]
At the moment there are 12 specified positions for charges in orle, if there are fewer charges then some positions are missed out. This works for some numbers but not others (e.g. 10, 11). It would nice to support more as well. Needs additions to arrangements.inc

**Comment by ericscheid** [comment]
I can't help thinking that there's a pattern that might arise from `mod(n,4)`

0. each side has same number of charges
1. the extra one is on top
2. the two extra are on the two sides
3. the one missing is from the bottom

Then, once things get crowded (13+ charges), we can put a charge each right in the top-dexter/top-sinister corners and (not) double-count them, distributing the rest along the dexter-base-sinister edges evenly (i.e. using those 2 from the top edge as being the anchors). Again, `mod(n,4) == 1` determining when an extra is added to the top edge.

So, with 14 charges, that's 4 across the top (two in corners, two between, so divide the top edge into 3 segments fencepost style), and then `14-4+2 ⇒ "12"` (ahem) charges to distribute, so `12 - 1 ⇒ 11` segments running dexter→base→sinister.

**Comment by karlwilcox** [comment]
Superceded by #272
