### ISSUE TITLE
!todo serpent vorant child colour (finished)

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#562]
!todo serpent vorant child colour (finished)

**Comment by PaoloRuben** [comment]
![serpent-erect-vorant-a-child](https://user-images.githubusercontent.com/57675116/212741994-a2507186-3dd0-40bd-bb4a-6fa08935b011.svg)

**Comment by PaoloRuben** [comment]
added child coloration

**Comment by PaoloRuben** [comment]
is it possible to make it crowned?

**Comment by karlwilcox** [comment]
All done, including the crown

**Comment by PaoloRuben** [comment]
💪🏻
