### ISSUE TITLE
!todo fix enty in point

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#568]
!todo fix enty in point
enty in point is offcenter

**Comment by PaoloRuben** [comment]
<img width="477" alt="image" src="https://user-images.githubusercontent.com/57675116/213883481-1abdbec7-da73-4a58-9d65-3196d425d939.png">

**Comment by PaoloRuben** [comment]
<img width="466" alt="image" src="https://user-images.githubusercontent.com/57675116/213883485-a9e64bce-1d24-4306-a229-1ca5741ef3fd.png">

**Comment by karlwilcox** [comment]
Not sure what we are looking at here, this is the current enty in point
![enty-in-point](https://user-images.githubusercontent.com/3171760/213889577-b87d75fc-7be1-4923-83a6-54ecb752d1b8.png)

**Comment by PaoloRuben** [comment]
And it's offset to the left

**Comment by PaoloRuben** [comment]
It becomes apparent when there's a division per pale

**Comment by PaoloRuben** [comment]
The two screenshots are the zoomed in alignment to the center, unfortunately as far as I know entry in point is coded and not a .SVG so I can't help further

**Comment by karlwilcox** [comment]
Can you give me the example blazon, thanks!

**Comment by PaoloRuben** [comment]
Per pale sable argent enty in point or

**Comment by PaoloRuben** [comment]
But even with only one colour the enty still isn't centered, if you look closely the sinister side is shorter

**Comment by karlwilcox** [comment]
Got it! Sorry, I wasn't zooming in enough, I see what you mean

**Comment by PaoloRuben** [comment]
It's very subtle, but it was bothering me to no end

**Comment by karlwilcox** [comment]
A slightly better version is now on the development system
