### ISSUE TITLE
!todo Elvin plate 18 fixes

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#569]
!todo Elvin plate 18 fixes

**Comment by ericscheid** [comment]
https://drawshield.net/reference/elvin/plate18.html

1. the image of the plate is missing entirely
2. the numbering is off - `21` on the plate (the big fancy centrepiece) is listed in the 20th `<li>` 

The 10th `<li>` has two entries conflated 
- [Bend Traverse, Counter-Pointed](https://drawshield.net/reference/elvin/b/bend-traverse.html). P. 18, f.9.
- [Bend Escartele, Grady, Or Embattled Grady](https://drawshield.net/reference/elvin/b/bend-escartele-1.html). P. 18, f. 10.

What should be the 40th `<li>` is actually split into two list items .. 
- Bendy sinister-paly. For Bendy
- Paly see P. 2. f. 32.

.. should be 
- Bendy sinister-paly. For Bendy Paly see P. 2. f. 32.


![image](https://user-images.githubusercontent.com/2605467/213919415-4f30fb41-7fe8-41b3-a39c-099598bdc060.png)
