### ISSUE TITLE
!todo `counter passant` does not work

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#576]
!todo `counter passant` does not work

**Comment by ericscheid** [comment]
It's in the arrangment of charges docs
https://drawshield.net/catalog/arrangements/index.html
<img width="190" alt="image" src="https://user-images.githubusercontent.com/2605467/220002250-cf1151b9-9ce8-4154-bda9-a27fb2167500.png">

It used to.. 
https://drawshield.net/gallery/0036/gallery-003626.html
![image](https://user-images.githubusercontent.com/2605467/220002122-7cd83e1c-15f1-451c-bae4-602f6733f700.png)

**Comment by karlwilcox** [comment]
Ah, for the moment you have to say "in counter passant", which does work, but "counter passant" should be valid on its own. I will look at a fix
