### ISSUE TITLE
!todo `bretessed` as edge treatment

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#577]
!todo `bretessed` as edge treatment
similar to `embattled counter embattled`, but with projections not interleaved offset
see http://scaheraldry.info/index.php?title=Embattled_and_Bretessed

**Comment by karlwilcox** [comment]
The edge treatment "embattled brettese" is already supported, I've added bretessed as a synonym.

**Comment by ericscheid** [comment]
Ah, I see it now in the catalog as `Embattled Brettessy` too. (That spelling was foiling my searching)
