### ISSUE TITLE
!todo `compass rose` centering

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#582]
!todo `compass rose` centering
The visual centre of the compass rose charge should not be the geometric centre of the charge bounding box.

**Comment by ericscheid** [comment]
<img width="537" alt="per bend" src="https://user-images.githubusercontent.com/2605467/222942847-0877220c-164b-4fd7-820e-ba438842da41.png">

<img width="471" alt="per fess" src="https://user-images.githubusercontent.com/2605467/222942843-25b25fa0-d11a-4184-9807-45b3b7159170.png">

**Comment by ericscheid** [comment]
..or is the problem the charge placement itself isn't exactly centered?

Nope — the charge top edge is 40px from the square top, as is the bottom edge.

<img width="676" alt="drawn in a square shape" src="https://user-images.githubusercontent.com/2605467/222942919-98dccf28-179c-4c2d-b010-553ce76953f3.png">

**Comment by karlwilcox** [comment]
Good point - there may well be other charges with this characteristic. The issue arises because the charge is centered on its "bounding box" (i.e. its maximum extents) rather than its "natural" centre (which of course may be different for each charge). 

Proper fix: add some charge metadata to apply an appropriate adjustment 

Quick fix: adjust the bounding box so it's centre is in the right place (so the pointy bit at the top is outside the box but still visible. 

I'll do the quick fix for now but think about the proper one!

**Comment by ericscheid** [comment]
Apart from obvious geometric shapes with bits sticking out to unbalance the bounding box, there are likely also a few animal charges that don't have the best match with visual centres (particularly regarding to dexter/sinister).

**Comment by karlwilcox** [comment]
The quick fix works well, so we should go with that for now. It might break "conjoined" charges but that is less of a problem than incorrect placement. If any other charges are like this just raise an issue for it.

**Comment by ericscheid** [comment]
There's still a slight offset if you look closely. My suggestion of "40px" might not have been precise.

<img width="912" alt="image" src="https://user-images.githubusercontent.com/2605467/230250678-80c4d690-5925-4294-8807-1296b35bd1fb.png">
<img width="882" alt="image" src="https://user-images.githubusercontent.com/2605467/230250738-2821732f-4b5c-4677-9053-4fa7fd2bc510.png">
<img width="852" alt="image" src="https://user-images.githubusercontent.com/2605467/230250915-d5222a28-4b00-4642-8d8d-03a4b1b8a31b.png">

**Comment by karlwilcox** [comment]
Yes, it is quite hard to get the centre point right by adjusting the boundary - I'm going to look at a different technique and have a bit of metadata that specifies the exact centre by coordinates.
