### ISSUE TITLE
!todo fix SVG of `dove volant`

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#584]
!todo fix SVG of `dove volant`
A stray block to the lower right.
!draw sable, a dove volant of argent very much smaller

**Comment by ericscheid** [comment]
![The ships hung in the sky in much the same way that bricks don't.](https://user-images.githubusercontent.com/2605467/223668739-76e6f5af-ac81-4915-af27-a1c7fac44bb7.png)
