### ISSUE TITLE
!todo `bordure` is failing

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#587]
!todo `bordure` is failing
`vert a bordure argent` produces a green shield .. but with a tiny trace of the bordure along the bottom edges

**Comment by ericscheid** [comment]
![see how the bottom edge of this shield has a white tracing .. against this white page .. oh](https://user-images.githubusercontent.com/2605467/226611111-b4ee54e4-4858-4491-b560-14d259463259.png)

harrumph .. lets try `cendree a bordure gules` instead

![image](https://user-images.githubusercontent.com/2605467/226611415-9a546ee2-1b8b-44df-b06b-edb7b80bf885.png)

**Comment by ericscheid** [comment]
<img width="603" alt="image" src="https://user-images.githubusercontent.com/2605467/226612014-7d23fdf6-4f16-405f-a41c-3c6f70689147.png">

**Comment by blackfog** [comment]
Hi. Don’t want to be a pest, but is there an ETA for when this may be fixed…even if it’s just to roll back whatever change broke it in the last merge?

**Comment by karlwilcox-ou** [comment]
Apologies, this is fixed, it is my github admin that is getting behind… the most up to date changes can be found on the Discord #announcements channel.
