### ISSUE TITLE
!todo `two charges in saltire` appear too low

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#591]
!todo `two charges in saltire` appear too low
!draw azure, a cross sable
two chains shown much larger in saltire argent
four moons decrescent in cross or

**Comment by ericscheid** [comment]
![image](https://user-images.githubusercontent.com/2605467/227768960-8a4a7b3b-633d-4848-a4f1-73e914e15772.png)

**Comment by karlwilcox** [comment]
Need to update the logic in arrangements.inc lines 770-790. (There is already a comment "there may be more to do here"!)

**Comment by karlwilcox** [comment]
The logic to determine whether some set of one or more charges should occupy as much of the shield as possible, or be carefully centred on the cross point is complex and there will be situations when it is wrong. As a sort-of fix I've added the charge modifier "centered" (or "at/on cross point") which will force the charge (or arrangement of charges) to be centred where the arms of the cross meet. Hence the above issue can be addressed with:

!draw azure, a cross sable
two chains shown much larger in saltire centered argent
four moons decrescent in cross or

I'll put this on the DEV system soon
