### ISSUE TITLE
two keys in saltire

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#6]
Two keys in saltire should convert internally to a pair of keys

**Comment by zifyoip** [comment]
Is this still a desired change? It seems that "two keys in saltire" is now supported, implemented by crossing two "key" charges, which is different from "a pair of keys". Is the desired behaviour specifically "a pair of keys"?

Azure, a key or.
![Azure, a key or](https://user-images.githubusercontent.com/62176468/78938942-7510ee80-7ab3-11ea-9b2b-2924ad7f8b7f.png)

Azure, two keys in saltire or.
![Azure, two keys in saltire or](https://user-images.githubusercontent.com/62176468/78939015-9e317f00-7ab3-11ea-83c8-102d7f2ccf3f.png)

Azure, a pair of keys or.
![Azure, a pair of keys or](https://user-images.githubusercontent.com/62176468/78939056-b43f3f80-7ab3-11ea-9972-0cf8c2b9bdd3.png)

If "pair of keys" is the desired behaviour, I can try to do that.

**Comment by karlwilcox** [comment]
Correct, this is not needed any more
