### ISSUE TITLE
!todo `a scythe handled` has an XML error

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#601]
!todo `a scythe handled` has an XML error
The `fill-opacity` attribute is re-defined in the same element in 5 instances.
> <path d="m 274.6,476.4 c -1.5,13.8 15.4,20.7 15.9,20.9" fill-opacity="0.75" fill-rule="evenodd" stroke="#000000" stroke-width="2" fill-opacity="0.999" />

**Comment by ericscheid** [comment]
`<path d="m 274.6,476.4 c -1.5,13.8 15.4,20.7 15.9,20.9" fill-opacity="0.75" fill-rule="evenodd" stroke="#000000" stroke-width="2" fill-opacity="0.999" />`

It used to work, as seen here:

https://drawshield.net/gallery/78/gallery-7889.html
![image](https://user-images.githubusercontent.com/2605467/237024234-f785c706-03a7-40f9-b418-3ff5b379b90f.png)
