### ISSUE TITLE
!todo `Cross of Legionnaire` renders as `Cross of Burgundy`

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#603]
!todo `Cross of Legionnaire` renders as `Cross of Burgundy`
https://drawshield.net/catalog/charges/quadrate/index.html

**Comment by ericscheid** [comment]
<img width="440" alt="image" src="https://github.com/drawshield/Drawshield-Code/assets/2605467/1cc9db8b-dc63-41c5-b2b5-2a9536d4bb6f">

<img width="389" alt="image" src="https://github.com/drawshield/Drawshield-Code/assets/2605467/3da3b305-bb5c-4adb-b78c-ec51a4d669c5">

<img width="588" alt="image" src="https://github.com/drawshield/Drawshield-Code/assets/2605467/1e286711-5623-44ac-b76b-2fd6bf58091c">
