### ISSUE TITLE
The Visual Catalog Item Finder textbox appears as a dropdown list instead

### ISSUE THREAD

**Issue by 5ucur** [drawshield/Drawshield-Code#617]
It is impossible to type into the Item Finder as it is now, therefore rendering it largely unusable. You can only type the names from the beginning, so finding `astronomical symbol for sun` by typing `sun`, or `elephant maintaining a tower on its back` by typing `tower`, is impossible. You would have to type `astronomical` or `elephant` to only get close to these example items.

Happens on Arch Linux and Windows 7, both using Firefox.

**Comment by karlwilcox** [comment]
Yes, thanks for reminding about this. I'm hoping to use something like the select2.js library to implement a better search but I'm not very good at JavaScript. I'll see what I can figure out!

**Comment by 5ucur** [comment]
I suppose this can be closed, as the textbox is back?
