### ISSUE TITLE
!todo `base pointed` is off-centre

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#622]
!todo `base pointed` is off-centre
!draw gules 
a cross-doubled argent 
a base pointed azure
a grid black

**Comment by ericscheid** [comment]
![image](https://github.com/drawshield/Drawshield-Code/assets/2605467/4ef7d7f0-f919-47ad-bef9-8cc03aa8184f)

**Comment by karlwilcox** [comment]
Small typo fixed, thanks for reporting
