### ISSUE TITLE
!todo The anteater's armed doesn't color the claws on the top hand

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#626]
!todo The anteater's armed doesn't color the claws on the top hand
argent an anteater rampant gules armed azure
The anteater's armed doesn't color the claws on the top hand

**Comment by ericscheid** [comment]
![image](https://github.com/drawshield/Drawshield-Code/assets/2605467/70faa5f8-ef1c-4e71-9abb-0aac65b1aa11)
