### ISSUE TITLE
!todo `cross flory` charge is now ordinary

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#633]
!todo `cross flory` charge is now ordinary

**Comment by ericscheid** [comment]
should be:
<img width="249" alt="image" src="https://github.com/drawshield/Drawshield-Code/assets/2605467/24bbb276-27b4-4cb0-a19a-72ca46768b36">

but is now:
<img width="511" alt="image" src="https://github.com/drawshield/Drawshield-Code/assets/2605467/db72c40d-2da2-4b02-83d4-e13c62efa99c">
