### ISSUE TITLE
!todo bull armed borked

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#641]
!todo bull armed borked
`a bull statant Sable armed Or` is not armed Or
`a bull Sable armed Or` only has one horn as Or

**Comment by ericscheid** [comment]
![a bull statant Sable armed Or](https://github.com/drawshield/Drawshield-Code/assets/2605467/4b9c224f-e811-422f-aeef-ca3e744381d8)

![a bull Sable armed Or](https://github.com/drawshield/Drawshield-Code/assets/2605467/9ce88af6-a971-4614-a9ac-0b2c35221aa0)

**Comment by karlwilcox** [comment]
There was a discussion (sorry, I forget where) in which was decided the following names for features:

**armed** - applies to teeth of all creatures and to the claws of things like lions and dragons
**attired** - applies only to antlers of deer, moose etc.
**horned** - applies to all creatures that have actual horns (like antelopes, bulls, goats etc.)

So the above creatures should be "horned" (the plain bull was a typo - the other horn is indeed "horned")

However, issue #600 also added some code which made "armed" synonymous with "horned" *unless* both were present - in this way, if there is something with both horns and teeth you can give them different colours. For clarity I suggest using "horned" where possible.

This should become clearer when I update the visual catalog.

**Comment by ericscheid** [comment]
ahh .. much better

<img width="520" alt="a bull Sable horned Or" src="https://github.com/drawshield/Drawshield-Code/assets/2605467/7308a327-97f5-4ee2-b02f-5d777887cd13">
