### ISSUE TITLE
`Per bend sinister` in flag shape reports an error in /svg/pathtools.inc

### ISSUE THREAD

**Issue by 5ucur** [drawshield/Drawshield-Code#642]
A blazon like `Per bend sinister, Gules and Sable` with the flag shape (the ratio seems not to matter) gives the following error (or warning?):

`/svg/pathtools.inc:181 : preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated`

Also, the split does not go cleanly from corner to corner, like the bend dexter one does (which also doesn't give the error). Example follows.
<details>
<summary> Image example here </summary>

![example](https://github.com/drawshield/Drawshield-Code/assets/28569802/f0e1206e-d837-4c68-a61c-f20fb686eae3)
</details>

For now, the workaround is to make a mirrored flag and flip it after export, but the error/warning is the main reason I'm reporting this.

**Comment by karlwilcox** [comment]
Thanks for spotting this. Couple of typos, will upload changes soon

**Comment by 5ucur** [comment]
It's been fixed! Closing this for you.
