### ISSUE TITLE
!todo `pomegranate` should have white pith, not red

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#646]
!todo `pomegranate` should have white pith, not red

**Comment by ericscheid** [comment]
When a `pomegranate` charge is placed, there is a red tint applied to the pith surrounding the fruit. Even if the charge is placed without any mention of `gules`.

`argent a pomegranate cendree fructed cendree leaved cendree`
<img width="719" alt="image" src="https://github.com/drawshield/Drawshield-Code/assets/2605467/65d6a7fc-1802-4ada-b8be-2af4a5d7f72e">

![image](https://github.com/drawshield/Drawshield-Code/assets/2605467/9e90d51a-85cd-47db-bb1a-b2bad0b13ccd)
