### ISSUE TITLE
Implement Juńczyk cross? (Feature req)

### ISSUE THREAD

**Issue by 7800uk** [drawshield/Drawshield-Code#651]
Polish nobility, Ukrainian hetmans, etc often used a special cross which [Wikipedia](https://en.wikipedia.org/wiki/Juńczyk_coat_of_arms) describes as a "double cross torn into a mustache." It seems like this charge was in use by several families across eastern Europe.

![hetmancross](https://github.com/drawshield/Drawshield-Code/assets/12129356/b6435c20-20ab-4161-acb1-282cfd29fb12)

I'm not super experienced with PHP, but I'd be willing to submit a PR to implement this charge in a few days' time.

**Comment by karlwilcox** [comment]
I can add this, I'll just call it a juncyk cross for now.
