### ISSUE TITLE
Improvements to achievements

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#66]
Summary: See highlight.

Correspondence:

I’ve answered your points below in rubric.

Also, for reference and by way of further explanation, I have attached some notes, which I think are best looked at first

Ecclesiastical achievements would be terrific but they are all hats.  Can you also allow the current charge “mitre” to be used in the same way as the helmet in an achievement?  As its lappets fall round the shoulders of the escutcheon it would have to be an alternative to helmet-and-mantling, as would the other ecclesiastical hats-and-cords

In my notes, for a lady’s arms in a lozenge or oval shape, I mentioned a love knot as (part of) an achievement.  I thought it might be a form of  torse.  On reflection, though, a love knot, too, has to wrap round the lozenge/oval, so it’s more like mantling. 

If any of the above are introduced, it would mean that the word “achievement” shouldn’t automatically produce anything.   Indeed, **the word ‘achievement’ becomes only an introductory warning that what follows isn’t on the shield/lozenge/oval.  And all elements of an achievement, except helmet and mantling, are independent of each other.**

I have responded below on this basis and, if you adopt this proposal, blazons would be like this:

(1) Sable on a bend Or 3 martlets bendwise sinister gules very much larger
Achievement
Torse sa and arg
Crest a demi lion per fess or and sable

(2) Sable a pile throughout inverted arg
Achievement
Torse arg and sa
Crest a talbot sejant gu
Motto “Loyaute mon honeur”

(3)  Barry  arg and gu
Achievement
Mantling dexter arg and gu sinister gu and arg  [whereupon a squire’s helmet will automatically appear, default colour steel]
Torse gu and arg
Crest a rustre sa

(4) Vert a pomegranate or fructed gu
Achievement
A Royal helmet Or [whereupon mantling will appear – the user can then colour it as he wishes]
Torse or and vert
Crest a lion rampant purpure

(5) Az a chi rho Or between 4 crosses crosslet arg
Achievement
A mitre az

(6) Or on a fess sa between 2 roses proper smaller  3 portcullises arg drawn in a lozenge shape
Achievement
A love knot az
Crest a baron’s coronet proper  [I know it’s not a crest but it’s in the same place as a crest]

**Comment by beoran** [comment]
An additional feature would be tehe ability to specify charges such as lions as shield bearers sinister and/or dexter. And also a pedestal under the shield and motto. Perhaps the key word flanked (dexter/sinister) could be used for the former, and a key word like on for the pedestal

**Comment by karlwilcox** [comment]
Thanks, Beoran, yes I would like to add that in future - the main issue is getting everything to fit neatly. I'm working on the eccelisiastical bits at the moment but will be looking at this later. Thanks for the suggestion.

**Comment by karlwilcox** [comment]
do you think you could add more than the helmets as headgear options  above the sheilds and add the different crowns already in the program? 

also would there be a way to add an option just to have the headgear and not the mantling around it?

because as as my old children's book on heraldry says,

![IMG_3093](https://user-images.githubusercontent.com/3171760/120836433-79248900-c55d-11eb-96b7-3c936f631f1d.jpg)

**Comment by karlwilcox** [comment]
How about a Bishop's Miter as a crest/helm?

**Comment by karlwilcox** [comment]
Further to the above, suggested mitre here https://commons.wikimedia.org/wiki/File:Roman_Catholic_Diocese_of_Orlando.svg

**Comment by karlwilcox** [comment]
Flowchart
![achievement-flowchart](https://user-images.githubusercontent.com/3171760/133839949-0f7021f9-f893-4304-8ac0-86081d90a2de.jpg)
:

**Comment by karlwilcox** [comment]
Most of this is done, so I'm going to close this in favour of smaller scale individual issues as required
