### ISSUE TITLE
When using the JSON API, images returned are empty

### ISSUE THREAD

**Issue by mirnovov** [drawshield/Drawshield-Code#677]
I use the Drawshield API for my [heraldtron](https://github.com/mirnovov/heraldtron/issues/16) bot. When querying a blazon using JSON, the image property is an empty string instead of base64-encoded data as intended. This causes the bot to fail, cf. mirnovov/heraldtron#16

Example: https://drawshield.net/include/drawshield.php?blazon=azure&outputformat=json

**Comment by karlwilcox** [comment]
Thanks, I'll look into that today.

**Comment by karlwilcox** [comment]
Apologies, this should be working now. The node.js image conversion service had stopped working, not sure why (pm2 is supposed to fix that sort of thing!). I do have a monitor on the HTTP service (uptime robot) but not on the image conversion service so I don't get notified about problems with that, I'll investigate ways to monitor it. Thanks for raising this!

**Comment by mirnovov** [comment]
No problem, appreciate your looking into it.
