### ISSUE TITLE
`Azure` uses the same dusty blue regardless of palette

### ISSUE THREAD

**Issue by 5ucur** [drawshield/Drawshield-Code#682]
Regardless of palette, the keyword `Azure` creates a dusty sort of blue, even in hatching or outline palettes. It happens regardless of whether the non-heraldic tinctures are enabled. `Az` works as a workaround for now, generates the correct Azure per palette. `Celestial azure` works normally.

I haven't used the site in a fair bit so I don't know how new this problem is.

<details>

<summary>Screenshots here, to demonstrate</summary>

![2024-10-29_15-35](https://github.com/user-attachments/assets/c3ead883-df0a-4f03-91b4-f81ddadd40dc)
![2024-10-29_15-35_1](https://github.com/user-attachments/assets/d6e40c18-bd38-4886-aa0a-0557cbaa2f22)

</details>

**Comment by karlwilcox** [comment]
Apologies for the delay in replying.

I suspect that you have enabled "Tartan" colours in the preferences pane - Azure in tartan is a different colour, so either disable the extre tartan colours or use "heraldic azure"  in your blazon instead. Please see the discussion here https://drawshield.net/docs/extensions/extra-colours.html which I will make more prominent!

Hope that helps,

Karl

**Comment by 5ucur** [comment]
The "Tartan" option was disabled, as well as the other colour options. However, now it doesn't happen anymore, so I suppose this is resolved. Thanks also for the "heraldic azure" keyword (keyphrase?)!
