### ISSUE TITLE
Spurious Error Message in per pile

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#7]
per pile purpure and sable 

Generates

parser Missing tincture(s) on division per pile purpure and sable   near line  Malformed tincture ID=N1-8 

(Caused by always looking for a third tincture - clean up in references.inc?)

**Comment by zifyoip** [comment]
I think this has been fixed—is there more to do?

Per pile purpure and sable.
![Per pile purpure and sable](https://user-images.githubusercontent.com/62176468/78939455-7abb0400-7ab4-11ea-904e-02a59f94c0bc.png)
(no warnings)

**Comment by karlwilcox** [comment]
This has been resolved, Per pile may have either two or three colours, Any other amount generates an error.
