### ISSUE TITLE
A pall inverted between three charges rendered incorrectly

### ISSUE THREAD

**Issue by bmeznarsic** [drawshield/Drawshield-Code#8]
- The pall itself is off center (to dexter) and 

- the three charges should be layed out as two and one vs one and two. 

![shield(2)](https://user-images.githubusercontent.com/6306479/68870004-65ef6580-06fa-11ea-9951-243f811beba3.png)

**Comment by karlwilcox** [comment]
Yes, you are correct, this was very sloppy! You can check positions by using the special charge "grid", for example " Argent a pall inverted azure a grid sable " will show this error quite clearly. I will add to to the TODO list and get it fixed... Thanks for reporting this.

**Comment by karlwilcox** [comment]
Now fixed

**Comment by bmeznarsic** [comment]
The three charges still don't get layed out as two and one. http://drawshield.net/create/index.html?blazon=Sable%20a%20pall%20inverted%20argent%20between%20three%20bezants

**Comment by karlwilcox** [comment]
Fixed, and I've stopped the roundels stretching...

Thanks for getting in touch,

all the best,

Karl

—
Karl R. Wilcox
Creator: Leading heraldry site drawshield.net
E-mail: karlwilcox36@gmail.com
Website: karlwilcox.com <http://www.karlwilcox.com>
LinkedIn: linkedin.com/in/karlwilcox <http://www.linkedin.com/in/karlwilcox>
Github: github.com/karlwilcox
